/* Generated by tools/type_registry/generate.py from types/registry.json. DO NOT EDIT. */
/* A semantic change requires a distinct TypeRef; prose never mutates an existing identity. */
#ifndef KSPACEJET_PROVIDER_TYPE_REGISTRY_H_
#define KSPACEJET_PROVIDER_TYPE_REGISTRY_H_

#include "kspacejet/provider/provider.h"

// clang-format off

/* ksj.kspace-frame: One complete multi-channel Cartesian k-space frame for reconstruction and k-space conditioning operators. */
/* Structural payload: complex_float32 channel_major_contiguous rank 3 [channel, ky, kx]. */
/* Payload semantics: {"completion":"All declared ky lines for the logical frame are present before publication.","dimension_meanings":{"channel":"receive_channel","kx":"cartesian_readout_sample","ky":"cartesian_phase_encode_line"},"numeric_encoding":"little_endian_interleaved_ieee754_binary32_real_imaginary","payload_role":"complete_cartesian_kspace_frame"} */
/* Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; scan and plan metadata remain control-plane artifacts."} */
static const char ksj_type_registry_kspace_frame_type_ref_storage[] = "ksj.kspace-frame";
static const ksj_utf8_view ksj_type_registry_kspace_frame_type_ref = {
  {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  ksj_type_registry_kspace_frame_type_ref_storage,
  sizeof(ksj_type_registry_kspace_frame_type_ref_storage) - 1U
};
static const ksj_utf8_view ksj_type_registry_kspace_frame_dimension_names[] = {
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "channel",
    sizeof("channel") - 1U
  },
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "ky",
    sizeof("ky") - 1U
  },
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "kx",
    sizeof("kx") - 1U
  },
};
static const uint64_t ksj_type_registry_kspace_frame_stride_bytes[8] = {
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
};
static const ksj_digest256 ksj_type_registry_kspace_frame_identity_digest =
{
  {sizeof(ksj_digest256), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  {
    UINT8_C(0xc8), UINT8_C(0xcd), UINT8_C(0x51), UINT8_C(0x55), UINT8_C(0x91), UINT8_C(0xbd), UINT8_C(0x7b), UINT8_C(0x70),
    UINT8_C(0x49), UINT8_C(0xe4), UINT8_C(0xb4), UINT8_C(0xdd), UINT8_C(0x5c), UINT8_C(0x20), UINT8_C(0x7a), UINT8_C(0x39),
    UINT8_C(0x77), UINT8_C(0xbb), UINT8_C(0x6f), UINT8_C(0x46), UINT8_C(0x05), UINT8_C(0x3e), UINT8_C(0x9d), UINT8_C(0x39),
    UINT8_C(0x7e), UINT8_C(0x0d), UINT8_C(0x68), UINT8_C(0x47), UINT8_C(0x5c), UINT8_C(0xc0), UINT8_C(0x0d), UINT8_C(0xd9)
  }
}
;

static inline ksj_type_descriptor_view ksj_type_registry_kspace_frame(void) {
  ksj_type_descriptor_view descriptor = {0};
  descriptor.abi = ksj_provider_abi_header_make((uint32_t)sizeof(descriptor), UINT64_C(0));
  descriptor.type_ref = ksj_type_registry_kspace_frame_type_ref;
  descriptor.type_identity_digest = ksj_type_registry_kspace_frame_identity_digest;
  descriptor.payload_kind = KSJ_PAYLOAD_KIND_BUFFER_HANDLE;
  descriptor.element_type = KSJ_ELEMENT_TYPE_COMPLEX_FLOAT32;
  descriptor.rank = UINT32_C(3);
  descriptor.dimension_names = ksj_type_registry_kspace_frame_dimension_names;
  descriptor.layout_flags = KSJ_TYPE_LAYOUT_CHANNEL_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL;
  descriptor.stride_bytes[0U] = ksj_type_registry_kspace_frame_stride_bytes[0U];
  descriptor.stride_bytes[1U] = ksj_type_registry_kspace_frame_stride_bytes[1U];
  descriptor.stride_bytes[2U] = ksj_type_registry_kspace_frame_stride_bytes[2U];
  descriptor.stride_bytes[3U] = ksj_type_registry_kspace_frame_stride_bytes[3U];
  descriptor.stride_bytes[4U] = ksj_type_registry_kspace_frame_stride_bytes[4U];
  descriptor.stride_bytes[5U] = ksj_type_registry_kspace_frame_stride_bytes[5U];
  descriptor.stride_bytes[6U] = ksj_type_registry_kspace_frame_stride_bytes[6U];
  descriptor.stride_bytes[7U] = ksj_type_registry_kspace_frame_stride_bytes[7U];
  descriptor.allowed_memory_domains = KSJ_PROVIDER_MEMORY_HOST_PAGEABLE;
  descriptor.minimum_alignment = UINT32_C(64);
  descriptor.mutability = KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH;
  return descriptor;
}

static inline int ksj_type_registry_matches_kspace_frame(const ksj_type_descriptor_view* descriptor) {
  uint32_t index;
  if (descriptor == NULL || descriptor->type_ref.data == NULL ||
      descriptor->type_ref.size != ksj_type_registry_kspace_frame_type_ref.size ||
      descriptor->payload_kind != KSJ_PAYLOAD_KIND_BUFFER_HANDLE ||
      descriptor->element_type != KSJ_ELEMENT_TYPE_COMPLEX_FLOAT32 ||
      descriptor->rank != UINT32_C(3) ||
      descriptor->layout_flags != (KSJ_TYPE_LAYOUT_CHANNEL_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL) ||
      descriptor->allowed_memory_domains != (KSJ_PROVIDER_MEMORY_HOST_PAGEABLE) ||
      descriptor->minimum_alignment != UINT32_C(64) ||
      descriptor->mutability != KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH) {
    return 0;
  }
  for (index = UINT32_C(0); index < descriptor->type_ref.size; ++index) {
    if (descriptor->type_ref.data[index] != ksj_type_registry_kspace_frame_type_ref.data[index]) {
      return 0;
    }
  }
  for (index = UINT32_C(0); index < KSJ_PROVIDER_DIGEST256_SIZE; ++index) {
    if (descriptor->type_identity_digest.bytes[index] != ksj_type_registry_kspace_frame_identity_digest.bytes[index]) {
      return 0;
    }
  }
  if (descriptor->dimension_names == NULL) {
    return 0;
  }
  for (index = UINT32_C(0); index < UINT32_C(3); ++index) {
    uint64_t character_index;
    if (descriptor->dimension_names[index].data == NULL ||
        descriptor->dimension_names[index].size != ksj_type_registry_kspace_frame_dimension_names[index].size) {
      return 0;
    }
    for (character_index = UINT64_C(0);
         character_index < descriptor->dimension_names[index].size; ++character_index) {
      if (descriptor->dimension_names[index].data[character_index] != ksj_type_registry_kspace_frame_dimension_names[index].data[character_index]) {
        return 0;
      }
    }
  }
  for (index = UINT32_C(0); index < UINT32_C(8); ++index) {
    if (descriptor->stride_bytes[index] != ksj_type_registry_kspace_frame_stride_bytes[index]) {
      return 0;
    }
  }
  return 1;
}

/* ksj.noise-calibration-frame: One multi-channel complex noise-only calibration sample frame used to estimate a noise model. */
/* Structural payload: complex_float32 channel_major_contiguous rank 2 [channel, sample]. */
/* Payload semantics: {"completion":"All samples belonging to one noise-calibration frame are present before publication.","dimension_meanings":{"channel":"physical_receive_channel","sample":"noise_only_readout_sample"},"numeric_encoding":"little_endian_interleaved_ieee754_binary32_real_imaginary","payload_role":"noise_calibration_samples"} */
/* Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; calibration keying and scan metadata remain control-plane artifacts."} */
static const char ksj_type_registry_noise_calibration_frame_type_ref_storage[] = "ksj.noise-calibration-frame";
static const ksj_utf8_view ksj_type_registry_noise_calibration_frame_type_ref = {
  {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  ksj_type_registry_noise_calibration_frame_type_ref_storage,
  sizeof(ksj_type_registry_noise_calibration_frame_type_ref_storage) - 1U
};
static const ksj_utf8_view ksj_type_registry_noise_calibration_frame_dimension_names[] = {
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "channel",
    sizeof("channel") - 1U
  },
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "sample",
    sizeof("sample") - 1U
  },
};
static const uint64_t ksj_type_registry_noise_calibration_frame_stride_bytes[8] = {
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
};
static const ksj_digest256 ksj_type_registry_noise_calibration_frame_identity_digest =
{
  {sizeof(ksj_digest256), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  {
    UINT8_C(0x31), UINT8_C(0x2e), UINT8_C(0x21), UINT8_C(0x69), UINT8_C(0xad), UINT8_C(0xb6), UINT8_C(0x87), UINT8_C(0x5a),
    UINT8_C(0x8c), UINT8_C(0x83), UINT8_C(0xc7), UINT8_C(0x1c), UINT8_C(0x47), UINT8_C(0x01), UINT8_C(0xee), UINT8_C(0xc7),
    UINT8_C(0x0e), UINT8_C(0xed), UINT8_C(0x82), UINT8_C(0x35), UINT8_C(0x7d), UINT8_C(0x36), UINT8_C(0xef), UINT8_C(0xe4),
    UINT8_C(0xe2), UINT8_C(0xba), UINT8_C(0x00), UINT8_C(0x94), UINT8_C(0x95), UINT8_C(0xcc), UINT8_C(0xad), UINT8_C(0x84)
  }
}
;

static inline ksj_type_descriptor_view ksj_type_registry_noise_calibration_frame(void) {
  ksj_type_descriptor_view descriptor = {0};
  descriptor.abi = ksj_provider_abi_header_make((uint32_t)sizeof(descriptor), UINT64_C(0));
  descriptor.type_ref = ksj_type_registry_noise_calibration_frame_type_ref;
  descriptor.type_identity_digest = ksj_type_registry_noise_calibration_frame_identity_digest;
  descriptor.payload_kind = KSJ_PAYLOAD_KIND_BUFFER_HANDLE;
  descriptor.element_type = KSJ_ELEMENT_TYPE_COMPLEX_FLOAT32;
  descriptor.rank = UINT32_C(2);
  descriptor.dimension_names = ksj_type_registry_noise_calibration_frame_dimension_names;
  descriptor.layout_flags = KSJ_TYPE_LAYOUT_CHANNEL_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL;
  descriptor.stride_bytes[0U] = ksj_type_registry_noise_calibration_frame_stride_bytes[0U];
  descriptor.stride_bytes[1U] = ksj_type_registry_noise_calibration_frame_stride_bytes[1U];
  descriptor.stride_bytes[2U] = ksj_type_registry_noise_calibration_frame_stride_bytes[2U];
  descriptor.stride_bytes[3U] = ksj_type_registry_noise_calibration_frame_stride_bytes[3U];
  descriptor.stride_bytes[4U] = ksj_type_registry_noise_calibration_frame_stride_bytes[4U];
  descriptor.stride_bytes[5U] = ksj_type_registry_noise_calibration_frame_stride_bytes[5U];
  descriptor.stride_bytes[6U] = ksj_type_registry_noise_calibration_frame_stride_bytes[6U];
  descriptor.stride_bytes[7U] = ksj_type_registry_noise_calibration_frame_stride_bytes[7U];
  descriptor.allowed_memory_domains = KSJ_PROVIDER_MEMORY_HOST_PAGEABLE;
  descriptor.minimum_alignment = UINT32_C(64);
  descriptor.mutability = KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH;
  return descriptor;
}

static inline int ksj_type_registry_matches_noise_calibration_frame(const ksj_type_descriptor_view* descriptor) {
  uint32_t index;
  if (descriptor == NULL || descriptor->type_ref.data == NULL ||
      descriptor->type_ref.size != ksj_type_registry_noise_calibration_frame_type_ref.size ||
      descriptor->payload_kind != KSJ_PAYLOAD_KIND_BUFFER_HANDLE ||
      descriptor->element_type != KSJ_ELEMENT_TYPE_COMPLEX_FLOAT32 ||
      descriptor->rank != UINT32_C(2) ||
      descriptor->layout_flags != (KSJ_TYPE_LAYOUT_CHANNEL_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL) ||
      descriptor->allowed_memory_domains != (KSJ_PROVIDER_MEMORY_HOST_PAGEABLE) ||
      descriptor->minimum_alignment != UINT32_C(64) ||
      descriptor->mutability != KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH) {
    return 0;
  }
  for (index = UINT32_C(0); index < descriptor->type_ref.size; ++index) {
    if (descriptor->type_ref.data[index] != ksj_type_registry_noise_calibration_frame_type_ref.data[index]) {
      return 0;
    }
  }
  for (index = UINT32_C(0); index < KSJ_PROVIDER_DIGEST256_SIZE; ++index) {
    if (descriptor->type_identity_digest.bytes[index] != ksj_type_registry_noise_calibration_frame_identity_digest.bytes[index]) {
      return 0;
    }
  }
  if (descriptor->dimension_names == NULL) {
    return 0;
  }
  for (index = UINT32_C(0); index < UINT32_C(2); ++index) {
    uint64_t character_index;
    if (descriptor->dimension_names[index].data == NULL ||
        descriptor->dimension_names[index].size != ksj_type_registry_noise_calibration_frame_dimension_names[index].size) {
      return 0;
    }
    for (character_index = UINT64_C(0);
         character_index < descriptor->dimension_names[index].size; ++character_index) {
      if (descriptor->dimension_names[index].data[character_index] != ksj_type_registry_noise_calibration_frame_dimension_names[index].data[character_index]) {
        return 0;
      }
    }
  }
  for (index = UINT32_C(0); index < UINT32_C(8); ++index) {
    if (descriptor->stride_bytes[index] != ksj_type_registry_noise_calibration_frame_stride_bytes[index]) {
      return 0;
    }
  }
  return 1;
}

/* ksj.noise-model: One complex channel-domain noise whitening model produced from noise calibration data. */
/* Structural payload: complex_float32 row_major_contiguous rank 2 [output_channel, input_channel]. */
/* Payload semantics: {"completion":"The matrix completely defines the immutable whitening transform for its calibration key.","dimension_meanings":{"input_channel":"physical_receive_channel","output_channel":"whitened_receive_channel"},"numeric_encoding":"little_endian_interleaved_ieee754_binary32_real_imaginary","payload_role":"noise_whitening_matrix"} */
/* Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; calibration keying and model provenance remain control-plane artifacts."} */
static const char ksj_type_registry_noise_model_type_ref_storage[] = "ksj.noise-model";
static const ksj_utf8_view ksj_type_registry_noise_model_type_ref = {
  {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  ksj_type_registry_noise_model_type_ref_storage,
  sizeof(ksj_type_registry_noise_model_type_ref_storage) - 1U
};
static const ksj_utf8_view ksj_type_registry_noise_model_dimension_names[] = {
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "output_channel",
    sizeof("output_channel") - 1U
  },
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "input_channel",
    sizeof("input_channel") - 1U
  },
};
static const uint64_t ksj_type_registry_noise_model_stride_bytes[8] = {
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
};
static const ksj_digest256 ksj_type_registry_noise_model_identity_digest =
{
  {sizeof(ksj_digest256), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  {
    UINT8_C(0x59), UINT8_C(0x92), UINT8_C(0x9d), UINT8_C(0x10), UINT8_C(0x7e), UINT8_C(0x2d), UINT8_C(0xd3), UINT8_C(0x59),
    UINT8_C(0x4f), UINT8_C(0x35), UINT8_C(0xc5), UINT8_C(0x2b), UINT8_C(0xe9), UINT8_C(0x60), UINT8_C(0x9c), UINT8_C(0x1a),
    UINT8_C(0xf1), UINT8_C(0xff), UINT8_C(0x08), UINT8_C(0x53), UINT8_C(0x4b), UINT8_C(0xa9), UINT8_C(0xd8), UINT8_C(0x5d),
    UINT8_C(0x64), UINT8_C(0xa1), UINT8_C(0x35), UINT8_C(0xed), UINT8_C(0xb2), UINT8_C(0x60), UINT8_C(0x58), UINT8_C(0x3e)
  }
}
;

static inline ksj_type_descriptor_view ksj_type_registry_noise_model(void) {
  ksj_type_descriptor_view descriptor = {0};
  descriptor.abi = ksj_provider_abi_header_make((uint32_t)sizeof(descriptor), UINT64_C(0));
  descriptor.type_ref = ksj_type_registry_noise_model_type_ref;
  descriptor.type_identity_digest = ksj_type_registry_noise_model_identity_digest;
  descriptor.payload_kind = KSJ_PAYLOAD_KIND_BUFFER_HANDLE;
  descriptor.element_type = KSJ_ELEMENT_TYPE_COMPLEX_FLOAT32;
  descriptor.rank = UINT32_C(2);
  descriptor.dimension_names = ksj_type_registry_noise_model_dimension_names;
  descriptor.layout_flags = KSJ_TYPE_LAYOUT_ROW_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL;
  descriptor.stride_bytes[0U] = ksj_type_registry_noise_model_stride_bytes[0U];
  descriptor.stride_bytes[1U] = ksj_type_registry_noise_model_stride_bytes[1U];
  descriptor.stride_bytes[2U] = ksj_type_registry_noise_model_stride_bytes[2U];
  descriptor.stride_bytes[3U] = ksj_type_registry_noise_model_stride_bytes[3U];
  descriptor.stride_bytes[4U] = ksj_type_registry_noise_model_stride_bytes[4U];
  descriptor.stride_bytes[5U] = ksj_type_registry_noise_model_stride_bytes[5U];
  descriptor.stride_bytes[6U] = ksj_type_registry_noise_model_stride_bytes[6U];
  descriptor.stride_bytes[7U] = ksj_type_registry_noise_model_stride_bytes[7U];
  descriptor.allowed_memory_domains = KSJ_PROVIDER_MEMORY_HOST_PAGEABLE;
  descriptor.minimum_alignment = UINT32_C(64);
  descriptor.mutability = KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH;
  return descriptor;
}

static inline int ksj_type_registry_matches_noise_model(const ksj_type_descriptor_view* descriptor) {
  uint32_t index;
  if (descriptor == NULL || descriptor->type_ref.data == NULL ||
      descriptor->type_ref.size != ksj_type_registry_noise_model_type_ref.size ||
      descriptor->payload_kind != KSJ_PAYLOAD_KIND_BUFFER_HANDLE ||
      descriptor->element_type != KSJ_ELEMENT_TYPE_COMPLEX_FLOAT32 ||
      descriptor->rank != UINT32_C(2) ||
      descriptor->layout_flags != (KSJ_TYPE_LAYOUT_ROW_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL) ||
      descriptor->allowed_memory_domains != (KSJ_PROVIDER_MEMORY_HOST_PAGEABLE) ||
      descriptor->minimum_alignment != UINT32_C(64) ||
      descriptor->mutability != KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH) {
    return 0;
  }
  for (index = UINT32_C(0); index < descriptor->type_ref.size; ++index) {
    if (descriptor->type_ref.data[index] != ksj_type_registry_noise_model_type_ref.data[index]) {
      return 0;
    }
  }
  for (index = UINT32_C(0); index < KSJ_PROVIDER_DIGEST256_SIZE; ++index) {
    if (descriptor->type_identity_digest.bytes[index] != ksj_type_registry_noise_model_identity_digest.bytes[index]) {
      return 0;
    }
  }
  if (descriptor->dimension_names == NULL) {
    return 0;
  }
  for (index = UINT32_C(0); index < UINT32_C(2); ++index) {
    uint64_t character_index;
    if (descriptor->dimension_names[index].data == NULL ||
        descriptor->dimension_names[index].size != ksj_type_registry_noise_model_dimension_names[index].size) {
      return 0;
    }
    for (character_index = UINT64_C(0);
         character_index < descriptor->dimension_names[index].size; ++character_index) {
      if (descriptor->dimension_names[index].data[character_index] != ksj_type_registry_noise_model_dimension_names[index].data[character_index]) {
        return 0;
      }
    }
  }
  for (index = UINT32_C(0); index < UINT32_C(8); ++index) {
    if (descriptor->stride_bytes[index] != ksj_type_registry_noise_model_stride_bytes[index]) {
      return 0;
    }
  }
  return 1;
}

/* ksj.phase-reference-frame: One multi-channel complex Cartesian phase-reference frame used to estimate phase correction. */
/* Structural payload: complex_float32 channel_major_contiguous rank 3 [channel, reference_line, kx]. */
/* Payload semantics: {"completion":"All declared phase-reference lines for the logical frame are present before publication.","dimension_meanings":{"channel":"physical_receive_channel","kx":"cartesian_readout_sample","reference_line":"phase_reference_line"},"numeric_encoding":"little_endian_interleaved_ieee754_binary32_real_imaginary","payload_role":"phase_reference_kspace_frame"} */
/* Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; phase-reference classification and keying remain control-plane artifacts."} */
static const char ksj_type_registry_phase_reference_frame_type_ref_storage[] = "ksj.phase-reference-frame";
static const ksj_utf8_view ksj_type_registry_phase_reference_frame_type_ref = {
  {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  ksj_type_registry_phase_reference_frame_type_ref_storage,
  sizeof(ksj_type_registry_phase_reference_frame_type_ref_storage) - 1U
};
static const ksj_utf8_view ksj_type_registry_phase_reference_frame_dimension_names[] = {
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "channel",
    sizeof("channel") - 1U
  },
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "reference_line",
    sizeof("reference_line") - 1U
  },
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "kx",
    sizeof("kx") - 1U
  },
};
static const uint64_t ksj_type_registry_phase_reference_frame_stride_bytes[8] = {
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
};
static const ksj_digest256 ksj_type_registry_phase_reference_frame_identity_digest =
{
  {sizeof(ksj_digest256), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  {
    UINT8_C(0x0c), UINT8_C(0xb4), UINT8_C(0xbb), UINT8_C(0x4c), UINT8_C(0xc8), UINT8_C(0xe3), UINT8_C(0xce), UINT8_C(0xd5),
    UINT8_C(0x46), UINT8_C(0x51), UINT8_C(0xbb), UINT8_C(0xbe), UINT8_C(0xc7), UINT8_C(0xc6), UINT8_C(0x7e), UINT8_C(0x11),
    UINT8_C(0x13), UINT8_C(0xdf), UINT8_C(0x41), UINT8_C(0x2c), UINT8_C(0x21), UINT8_C(0xa0), UINT8_C(0xd4), UINT8_C(0xfa),
    UINT8_C(0x2b), UINT8_C(0xa2), UINT8_C(0x7a), UINT8_C(0x7c), UINT8_C(0x15), UINT8_C(0x7d), UINT8_C(0x3b), UINT8_C(0xb5)
  }
}
;

static inline ksj_type_descriptor_view ksj_type_registry_phase_reference_frame(void) {
  ksj_type_descriptor_view descriptor = {0};
  descriptor.abi = ksj_provider_abi_header_make((uint32_t)sizeof(descriptor), UINT64_C(0));
  descriptor.type_ref = ksj_type_registry_phase_reference_frame_type_ref;
  descriptor.type_identity_digest = ksj_type_registry_phase_reference_frame_identity_digest;
  descriptor.payload_kind = KSJ_PAYLOAD_KIND_BUFFER_HANDLE;
  descriptor.element_type = KSJ_ELEMENT_TYPE_COMPLEX_FLOAT32;
  descriptor.rank = UINT32_C(3);
  descriptor.dimension_names = ksj_type_registry_phase_reference_frame_dimension_names;
  descriptor.layout_flags = KSJ_TYPE_LAYOUT_CHANNEL_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL;
  descriptor.stride_bytes[0U] = ksj_type_registry_phase_reference_frame_stride_bytes[0U];
  descriptor.stride_bytes[1U] = ksj_type_registry_phase_reference_frame_stride_bytes[1U];
  descriptor.stride_bytes[2U] = ksj_type_registry_phase_reference_frame_stride_bytes[2U];
  descriptor.stride_bytes[3U] = ksj_type_registry_phase_reference_frame_stride_bytes[3U];
  descriptor.stride_bytes[4U] = ksj_type_registry_phase_reference_frame_stride_bytes[4U];
  descriptor.stride_bytes[5U] = ksj_type_registry_phase_reference_frame_stride_bytes[5U];
  descriptor.stride_bytes[6U] = ksj_type_registry_phase_reference_frame_stride_bytes[6U];
  descriptor.stride_bytes[7U] = ksj_type_registry_phase_reference_frame_stride_bytes[7U];
  descriptor.allowed_memory_domains = KSJ_PROVIDER_MEMORY_HOST_PAGEABLE;
  descriptor.minimum_alignment = UINT32_C(64);
  descriptor.mutability = KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH;
  return descriptor;
}

static inline int ksj_type_registry_matches_phase_reference_frame(const ksj_type_descriptor_view* descriptor) {
  uint32_t index;
  if (descriptor == NULL || descriptor->type_ref.data == NULL ||
      descriptor->type_ref.size != ksj_type_registry_phase_reference_frame_type_ref.size ||
      descriptor->payload_kind != KSJ_PAYLOAD_KIND_BUFFER_HANDLE ||
      descriptor->element_type != KSJ_ELEMENT_TYPE_COMPLEX_FLOAT32 ||
      descriptor->rank != UINT32_C(3) ||
      descriptor->layout_flags != (KSJ_TYPE_LAYOUT_CHANNEL_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL) ||
      descriptor->allowed_memory_domains != (KSJ_PROVIDER_MEMORY_HOST_PAGEABLE) ||
      descriptor->minimum_alignment != UINT32_C(64) ||
      descriptor->mutability != KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH) {
    return 0;
  }
  for (index = UINT32_C(0); index < descriptor->type_ref.size; ++index) {
    if (descriptor->type_ref.data[index] != ksj_type_registry_phase_reference_frame_type_ref.data[index]) {
      return 0;
    }
  }
  for (index = UINT32_C(0); index < KSJ_PROVIDER_DIGEST256_SIZE; ++index) {
    if (descriptor->type_identity_digest.bytes[index] != ksj_type_registry_phase_reference_frame_identity_digest.bytes[index]) {
      return 0;
    }
  }
  if (descriptor->dimension_names == NULL) {
    return 0;
  }
  for (index = UINT32_C(0); index < UINT32_C(3); ++index) {
    uint64_t character_index;
    if (descriptor->dimension_names[index].data == NULL ||
        descriptor->dimension_names[index].size != ksj_type_registry_phase_reference_frame_dimension_names[index].size) {
      return 0;
    }
    for (character_index = UINT64_C(0);
         character_index < descriptor->dimension_names[index].size; ++character_index) {
      if (descriptor->dimension_names[index].data[character_index] != ksj_type_registry_phase_reference_frame_dimension_names[index].data[character_index]) {
        return 0;
      }
    }
  }
  for (index = UINT32_C(0); index < UINT32_C(8); ++index) {
    if (descriptor->stride_bytes[index] != ksj_type_registry_phase_reference_frame_stride_bytes[index]) {
      return 0;
    }
  }
  return 1;
}

/* ksj.phase-model: One complex channel-by-readout phase correction model produced from phase-reference data. */
/* Structural payload: complex_float32 channel_major_contiguous rank 2 [channel, kx]. */
/* Payload semantics: {"completion":"The phasor covers every receive channel and readout sample required by its calibration key.","dimension_meanings":{"channel":"physical_receive_channel","kx":"cartesian_readout_sample"},"numeric_encoding":"little_endian_interleaved_ieee754_binary32_real_imaginary","payload_role":"phase_correction_phasor"} */
/* Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; calibration keying and model provenance remain control-plane artifacts."} */
static const char ksj_type_registry_phase_model_type_ref_storage[] = "ksj.phase-model";
static const ksj_utf8_view ksj_type_registry_phase_model_type_ref = {
  {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  ksj_type_registry_phase_model_type_ref_storage,
  sizeof(ksj_type_registry_phase_model_type_ref_storage) - 1U
};
static const ksj_utf8_view ksj_type_registry_phase_model_dimension_names[] = {
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "channel",
    sizeof("channel") - 1U
  },
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "kx",
    sizeof("kx") - 1U
  },
};
static const uint64_t ksj_type_registry_phase_model_stride_bytes[8] = {
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
};
static const ksj_digest256 ksj_type_registry_phase_model_identity_digest =
{
  {sizeof(ksj_digest256), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  {
    UINT8_C(0x53), UINT8_C(0xef), UINT8_C(0xfa), UINT8_C(0x04), UINT8_C(0x39), UINT8_C(0x96), UINT8_C(0xb6), UINT8_C(0x02),
    UINT8_C(0x5c), UINT8_C(0x78), UINT8_C(0xe6), UINT8_C(0x24), UINT8_C(0x15), UINT8_C(0xbc), UINT8_C(0x21), UINT8_C(0x75),
    UINT8_C(0xd5), UINT8_C(0xcd), UINT8_C(0x1f), UINT8_C(0x30), UINT8_C(0x60), UINT8_C(0xee), UINT8_C(0xce), UINT8_C(0x76),
    UINT8_C(0x29), UINT8_C(0x84), UINT8_C(0xd1), UINT8_C(0x9d), UINT8_C(0x55), UINT8_C(0xd7), UINT8_C(0xaf), UINT8_C(0x5a)
  }
}
;

static inline ksj_type_descriptor_view ksj_type_registry_phase_model(void) {
  ksj_type_descriptor_view descriptor = {0};
  descriptor.abi = ksj_provider_abi_header_make((uint32_t)sizeof(descriptor), UINT64_C(0));
  descriptor.type_ref = ksj_type_registry_phase_model_type_ref;
  descriptor.type_identity_digest = ksj_type_registry_phase_model_identity_digest;
  descriptor.payload_kind = KSJ_PAYLOAD_KIND_BUFFER_HANDLE;
  descriptor.element_type = KSJ_ELEMENT_TYPE_COMPLEX_FLOAT32;
  descriptor.rank = UINT32_C(2);
  descriptor.dimension_names = ksj_type_registry_phase_model_dimension_names;
  descriptor.layout_flags = KSJ_TYPE_LAYOUT_CHANNEL_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL;
  descriptor.stride_bytes[0U] = ksj_type_registry_phase_model_stride_bytes[0U];
  descriptor.stride_bytes[1U] = ksj_type_registry_phase_model_stride_bytes[1U];
  descriptor.stride_bytes[2U] = ksj_type_registry_phase_model_stride_bytes[2U];
  descriptor.stride_bytes[3U] = ksj_type_registry_phase_model_stride_bytes[3U];
  descriptor.stride_bytes[4U] = ksj_type_registry_phase_model_stride_bytes[4U];
  descriptor.stride_bytes[5U] = ksj_type_registry_phase_model_stride_bytes[5U];
  descriptor.stride_bytes[6U] = ksj_type_registry_phase_model_stride_bytes[6U];
  descriptor.stride_bytes[7U] = ksj_type_registry_phase_model_stride_bytes[7U];
  descriptor.allowed_memory_domains = KSJ_PROVIDER_MEMORY_HOST_PAGEABLE;
  descriptor.minimum_alignment = UINT32_C(64);
  descriptor.mutability = KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH;
  return descriptor;
}

static inline int ksj_type_registry_matches_phase_model(const ksj_type_descriptor_view* descriptor) {
  uint32_t index;
  if (descriptor == NULL || descriptor->type_ref.data == NULL ||
      descriptor->type_ref.size != ksj_type_registry_phase_model_type_ref.size ||
      descriptor->payload_kind != KSJ_PAYLOAD_KIND_BUFFER_HANDLE ||
      descriptor->element_type != KSJ_ELEMENT_TYPE_COMPLEX_FLOAT32 ||
      descriptor->rank != UINT32_C(2) ||
      descriptor->layout_flags != (KSJ_TYPE_LAYOUT_CHANNEL_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL) ||
      descriptor->allowed_memory_domains != (KSJ_PROVIDER_MEMORY_HOST_PAGEABLE) ||
      descriptor->minimum_alignment != UINT32_C(64) ||
      descriptor->mutability != KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH) {
    return 0;
  }
  for (index = UINT32_C(0); index < descriptor->type_ref.size; ++index) {
    if (descriptor->type_ref.data[index] != ksj_type_registry_phase_model_type_ref.data[index]) {
      return 0;
    }
  }
  for (index = UINT32_C(0); index < KSJ_PROVIDER_DIGEST256_SIZE; ++index) {
    if (descriptor->type_identity_digest.bytes[index] != ksj_type_registry_phase_model_identity_digest.bytes[index]) {
      return 0;
    }
  }
  if (descriptor->dimension_names == NULL) {
    return 0;
  }
  for (index = UINT32_C(0); index < UINT32_C(2); ++index) {
    uint64_t character_index;
    if (descriptor->dimension_names[index].data == NULL ||
        descriptor->dimension_names[index].size != ksj_type_registry_phase_model_dimension_names[index].size) {
      return 0;
    }
    for (character_index = UINT64_C(0);
         character_index < descriptor->dimension_names[index].size; ++character_index) {
      if (descriptor->dimension_names[index].data[character_index] != ksj_type_registry_phase_model_dimension_names[index].data[character_index]) {
        return 0;
      }
    }
  }
  for (index = UINT32_C(0); index < UINT32_C(8); ++index) {
    if (descriptor->stride_bytes[index] != ksj_type_registry_phase_model_stride_bytes[index]) {
      return 0;
    }
  }
  return 1;
}

/* ksj.coil-compression-basis: One complex basis mapping physical receive channels to virtual channels for coil compression. */
/* Structural payload: complex_float32 row_major_contiguous rank 2 [virtual_channel, physical_channel]. */
/* Payload semantics: {"completion":"The matrix completely defines the immutable compression transform for its calibration key.","dimension_meanings":{"physical_channel":"physical_receive_channel","virtual_channel":"compressed_receive_channel"},"numeric_encoding":"little_endian_interleaved_ieee754_binary32_real_imaginary","payload_role":"coil_compression_basis_matrix"} */
/* Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; calibration keying and basis provenance remain control-plane artifacts."} */
static const char ksj_type_registry_coil_compression_basis_type_ref_storage[] = "ksj.coil-compression-basis";
static const ksj_utf8_view ksj_type_registry_coil_compression_basis_type_ref = {
  {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  ksj_type_registry_coil_compression_basis_type_ref_storage,
  sizeof(ksj_type_registry_coil_compression_basis_type_ref_storage) - 1U
};
static const ksj_utf8_view ksj_type_registry_coil_compression_basis_dimension_names[] = {
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "virtual_channel",
    sizeof("virtual_channel") - 1U
  },
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "physical_channel",
    sizeof("physical_channel") - 1U
  },
};
static const uint64_t ksj_type_registry_coil_compression_basis_stride_bytes[8] = {
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
};
static const ksj_digest256 ksj_type_registry_coil_compression_basis_identity_digest =
{
  {sizeof(ksj_digest256), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  {
    UINT8_C(0x30), UINT8_C(0x8b), UINT8_C(0xc8), UINT8_C(0x28), UINT8_C(0xf8), UINT8_C(0x97), UINT8_C(0xfc), UINT8_C(0x24),
    UINT8_C(0x3f), UINT8_C(0xe6), UINT8_C(0x55), UINT8_C(0x95), UINT8_C(0xda), UINT8_C(0x70), UINT8_C(0x4f), UINT8_C(0x4b),
    UINT8_C(0x2d), UINT8_C(0x5b), UINT8_C(0xee), UINT8_C(0x1b), UINT8_C(0x92), UINT8_C(0xd7), UINT8_C(0x5a), UINT8_C(0x7b),
    UINT8_C(0xe6), UINT8_C(0x8e), UINT8_C(0xd7), UINT8_C(0x0d), UINT8_C(0x2c), UINT8_C(0x05), UINT8_C(0x66), UINT8_C(0xcf)
  }
}
;

static inline ksj_type_descriptor_view ksj_type_registry_coil_compression_basis(void) {
  ksj_type_descriptor_view descriptor = {0};
  descriptor.abi = ksj_provider_abi_header_make((uint32_t)sizeof(descriptor), UINT64_C(0));
  descriptor.type_ref = ksj_type_registry_coil_compression_basis_type_ref;
  descriptor.type_identity_digest = ksj_type_registry_coil_compression_basis_identity_digest;
  descriptor.payload_kind = KSJ_PAYLOAD_KIND_BUFFER_HANDLE;
  descriptor.element_type = KSJ_ELEMENT_TYPE_COMPLEX_FLOAT32;
  descriptor.rank = UINT32_C(2);
  descriptor.dimension_names = ksj_type_registry_coil_compression_basis_dimension_names;
  descriptor.layout_flags = KSJ_TYPE_LAYOUT_ROW_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL;
  descriptor.stride_bytes[0U] = ksj_type_registry_coil_compression_basis_stride_bytes[0U];
  descriptor.stride_bytes[1U] = ksj_type_registry_coil_compression_basis_stride_bytes[1U];
  descriptor.stride_bytes[2U] = ksj_type_registry_coil_compression_basis_stride_bytes[2U];
  descriptor.stride_bytes[3U] = ksj_type_registry_coil_compression_basis_stride_bytes[3U];
  descriptor.stride_bytes[4U] = ksj_type_registry_coil_compression_basis_stride_bytes[4U];
  descriptor.stride_bytes[5U] = ksj_type_registry_coil_compression_basis_stride_bytes[5U];
  descriptor.stride_bytes[6U] = ksj_type_registry_coil_compression_basis_stride_bytes[6U];
  descriptor.stride_bytes[7U] = ksj_type_registry_coil_compression_basis_stride_bytes[7U];
  descriptor.allowed_memory_domains = KSJ_PROVIDER_MEMORY_HOST_PAGEABLE;
  descriptor.minimum_alignment = UINT32_C(64);
  descriptor.mutability = KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH;
  return descriptor;
}

static inline int ksj_type_registry_matches_coil_compression_basis(const ksj_type_descriptor_view* descriptor) {
  uint32_t index;
  if (descriptor == NULL || descriptor->type_ref.data == NULL ||
      descriptor->type_ref.size != ksj_type_registry_coil_compression_basis_type_ref.size ||
      descriptor->payload_kind != KSJ_PAYLOAD_KIND_BUFFER_HANDLE ||
      descriptor->element_type != KSJ_ELEMENT_TYPE_COMPLEX_FLOAT32 ||
      descriptor->rank != UINT32_C(2) ||
      descriptor->layout_flags != (KSJ_TYPE_LAYOUT_ROW_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL) ||
      descriptor->allowed_memory_domains != (KSJ_PROVIDER_MEMORY_HOST_PAGEABLE) ||
      descriptor->minimum_alignment != UINT32_C(64) ||
      descriptor->mutability != KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH) {
    return 0;
  }
  for (index = UINT32_C(0); index < descriptor->type_ref.size; ++index) {
    if (descriptor->type_ref.data[index] != ksj_type_registry_coil_compression_basis_type_ref.data[index]) {
      return 0;
    }
  }
  for (index = UINT32_C(0); index < KSJ_PROVIDER_DIGEST256_SIZE; ++index) {
    if (descriptor->type_identity_digest.bytes[index] != ksj_type_registry_coil_compression_basis_identity_digest.bytes[index]) {
      return 0;
    }
  }
  if (descriptor->dimension_names == NULL) {
    return 0;
  }
  for (index = UINT32_C(0); index < UINT32_C(2); ++index) {
    uint64_t character_index;
    if (descriptor->dimension_names[index].data == NULL ||
        descriptor->dimension_names[index].size != ksj_type_registry_coil_compression_basis_dimension_names[index].size) {
      return 0;
    }
    for (character_index = UINT64_C(0);
         character_index < descriptor->dimension_names[index].size; ++character_index) {
      if (descriptor->dimension_names[index].data[character_index] != ksj_type_registry_coil_compression_basis_dimension_names[index].data[character_index]) {
        return 0;
      }
    }
  }
  for (index = UINT32_C(0); index < UINT32_C(8); ++index) {
    if (descriptor->stride_bytes[index] != ksj_type_registry_coil_compression_basis_stride_bytes[index]) {
      return 0;
    }
  }
  return 1;
}

/* ksj.coil-image-frame: One complex reconstructed Cartesian image frame retaining one value per receive channel at every pixel. */
/* Structural payload: complex_float32 row_major_contiguous rank 3 [ky, kx, channel]. */
/* Payload semantics: {"completion":"Every image pixel and receive channel for the logical frame is present before publication.","dimension_meanings":{"channel":"receive_channel_at_pixel","kx":"image_column_from_cartesian_readout_axis","ky":"image_row_from_cartesian_phase_encode_axis"},"numeric_encoding":"little_endian_interleaved_ieee754_binary32_real_imaginary","payload_role":"complex_coil_image_frame"} */
/* Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; scan and image-frame metadata remain control-plane artifacts."} */
static const char ksj_type_registry_coil_image_frame_type_ref_storage[] = "ksj.coil-image-frame";
static const ksj_utf8_view ksj_type_registry_coil_image_frame_type_ref = {
  {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  ksj_type_registry_coil_image_frame_type_ref_storage,
  sizeof(ksj_type_registry_coil_image_frame_type_ref_storage) - 1U
};
static const ksj_utf8_view ksj_type_registry_coil_image_frame_dimension_names[] = {
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "ky",
    sizeof("ky") - 1U
  },
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "kx",
    sizeof("kx") - 1U
  },
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "channel",
    sizeof("channel") - 1U
  },
};
static const uint64_t ksj_type_registry_coil_image_frame_stride_bytes[8] = {
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
};
static const ksj_digest256 ksj_type_registry_coil_image_frame_identity_digest =
{
  {sizeof(ksj_digest256), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  {
    UINT8_C(0xcb), UINT8_C(0x9c), UINT8_C(0x72), UINT8_C(0xb7), UINT8_C(0x14), UINT8_C(0x37), UINT8_C(0x69), UINT8_C(0xf3),
    UINT8_C(0x7f), UINT8_C(0x00), UINT8_C(0x2e), UINT8_C(0xcc), UINT8_C(0x29), UINT8_C(0x83), UINT8_C(0xb7), UINT8_C(0xf2),
    UINT8_C(0x44), UINT8_C(0x69), UINT8_C(0xc4), UINT8_C(0x0a), UINT8_C(0xf9), UINT8_C(0x5b), UINT8_C(0x4f), UINT8_C(0xb0),
    UINT8_C(0xbb), UINT8_C(0xc8), UINT8_C(0xbe), UINT8_C(0xf2), UINT8_C(0xb4), UINT8_C(0x74), UINT8_C(0x1a), UINT8_C(0x87)
  }
}
;

static inline ksj_type_descriptor_view ksj_type_registry_coil_image_frame(void) {
  ksj_type_descriptor_view descriptor = {0};
  descriptor.abi = ksj_provider_abi_header_make((uint32_t)sizeof(descriptor), UINT64_C(0));
  descriptor.type_ref = ksj_type_registry_coil_image_frame_type_ref;
  descriptor.type_identity_digest = ksj_type_registry_coil_image_frame_identity_digest;
  descriptor.payload_kind = KSJ_PAYLOAD_KIND_BUFFER_HANDLE;
  descriptor.element_type = KSJ_ELEMENT_TYPE_COMPLEX_FLOAT32;
  descriptor.rank = UINT32_C(3);
  descriptor.dimension_names = ksj_type_registry_coil_image_frame_dimension_names;
  descriptor.layout_flags = KSJ_TYPE_LAYOUT_ROW_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL;
  descriptor.stride_bytes[0U] = ksj_type_registry_coil_image_frame_stride_bytes[0U];
  descriptor.stride_bytes[1U] = ksj_type_registry_coil_image_frame_stride_bytes[1U];
  descriptor.stride_bytes[2U] = ksj_type_registry_coil_image_frame_stride_bytes[2U];
  descriptor.stride_bytes[3U] = ksj_type_registry_coil_image_frame_stride_bytes[3U];
  descriptor.stride_bytes[4U] = ksj_type_registry_coil_image_frame_stride_bytes[4U];
  descriptor.stride_bytes[5U] = ksj_type_registry_coil_image_frame_stride_bytes[5U];
  descriptor.stride_bytes[6U] = ksj_type_registry_coil_image_frame_stride_bytes[6U];
  descriptor.stride_bytes[7U] = ksj_type_registry_coil_image_frame_stride_bytes[7U];
  descriptor.allowed_memory_domains = KSJ_PROVIDER_MEMORY_HOST_PAGEABLE;
  descriptor.minimum_alignment = UINT32_C(64);
  descriptor.mutability = KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH;
  return descriptor;
}

static inline int ksj_type_registry_matches_coil_image_frame(const ksj_type_descriptor_view* descriptor) {
  uint32_t index;
  if (descriptor == NULL || descriptor->type_ref.data == NULL ||
      descriptor->type_ref.size != ksj_type_registry_coil_image_frame_type_ref.size ||
      descriptor->payload_kind != KSJ_PAYLOAD_KIND_BUFFER_HANDLE ||
      descriptor->element_type != KSJ_ELEMENT_TYPE_COMPLEX_FLOAT32 ||
      descriptor->rank != UINT32_C(3) ||
      descriptor->layout_flags != (KSJ_TYPE_LAYOUT_ROW_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL) ||
      descriptor->allowed_memory_domains != (KSJ_PROVIDER_MEMORY_HOST_PAGEABLE) ||
      descriptor->minimum_alignment != UINT32_C(64) ||
      descriptor->mutability != KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH) {
    return 0;
  }
  for (index = UINT32_C(0); index < descriptor->type_ref.size; ++index) {
    if (descriptor->type_ref.data[index] != ksj_type_registry_coil_image_frame_type_ref.data[index]) {
      return 0;
    }
  }
  for (index = UINT32_C(0); index < KSJ_PROVIDER_DIGEST256_SIZE; ++index) {
    if (descriptor->type_identity_digest.bytes[index] != ksj_type_registry_coil_image_frame_identity_digest.bytes[index]) {
      return 0;
    }
  }
  if (descriptor->dimension_names == NULL) {
    return 0;
  }
  for (index = UINT32_C(0); index < UINT32_C(3); ++index) {
    uint64_t character_index;
    if (descriptor->dimension_names[index].data == NULL ||
        descriptor->dimension_names[index].size != ksj_type_registry_coil_image_frame_dimension_names[index].size) {
      return 0;
    }
    for (character_index = UINT64_C(0);
         character_index < descriptor->dimension_names[index].size; ++character_index) {
      if (descriptor->dimension_names[index].data[character_index] != ksj_type_registry_coil_image_frame_dimension_names[index].data[character_index]) {
        return 0;
      }
    }
  }
  for (index = UINT32_C(0); index < UINT32_C(8); ++index) {
    if (descriptor->stride_bytes[index] != ksj_type_registry_coil_image_frame_stride_bytes[index]) {
      return 0;
    }
  }
  return 1;
}

/* ksj.complex-image-frame: One complex reconstructed two-dimensional image plane after channel combination or model-based reconstruction. */
/* Structural payload: complex_float32 row_major_contiguous rank 2 [ky, kx]. */
/* Payload semantics: {"completion":"Every complex output pixel for the logical frame is present before publication.","dimension_meanings":{"kx":"image_column_from_cartesian_readout_axis","ky":"image_row_from_cartesian_phase_encode_axis"},"numeric_encoding":"little_endian_interleaved_ieee754_binary32_real_imaginary","payload_role":"reconstructed_complex_image_plane"} */
/* Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; scan and image-frame metadata remain control-plane artifacts."} */
static const char ksj_type_registry_complex_image_frame_type_ref_storage[] = "ksj.complex-image-frame";
static const ksj_utf8_view ksj_type_registry_complex_image_frame_type_ref = {
  {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  ksj_type_registry_complex_image_frame_type_ref_storage,
  sizeof(ksj_type_registry_complex_image_frame_type_ref_storage) - 1U
};
static const ksj_utf8_view ksj_type_registry_complex_image_frame_dimension_names[] = {
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "ky",
    sizeof("ky") - 1U
  },
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "kx",
    sizeof("kx") - 1U
  },
};
static const uint64_t ksj_type_registry_complex_image_frame_stride_bytes[8] = {
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
};
static const ksj_digest256 ksj_type_registry_complex_image_frame_identity_digest =
{
  {sizeof(ksj_digest256), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  {
    UINT8_C(0x0d), UINT8_C(0x12), UINT8_C(0x41), UINT8_C(0xd2), UINT8_C(0x46), UINT8_C(0x06), UINT8_C(0xd4), UINT8_C(0x8f),
    UINT8_C(0x0a), UINT8_C(0xce), UINT8_C(0xf0), UINT8_C(0xd5), UINT8_C(0x55), UINT8_C(0x72), UINT8_C(0x07), UINT8_C(0x02),
    UINT8_C(0x25), UINT8_C(0xe6), UINT8_C(0xa4), UINT8_C(0x03), UINT8_C(0x7f), UINT8_C(0xc2), UINT8_C(0xe8), UINT8_C(0x70),
    UINT8_C(0x4d), UINT8_C(0xaf), UINT8_C(0xe5), UINT8_C(0x2e), UINT8_C(0x93), UINT8_C(0x5e), UINT8_C(0x94), UINT8_C(0x9a)
  }
}
;

static inline ksj_type_descriptor_view ksj_type_registry_complex_image_frame(void) {
  ksj_type_descriptor_view descriptor = {0};
  descriptor.abi = ksj_provider_abi_header_make((uint32_t)sizeof(descriptor), UINT64_C(0));
  descriptor.type_ref = ksj_type_registry_complex_image_frame_type_ref;
  descriptor.type_identity_digest = ksj_type_registry_complex_image_frame_identity_digest;
  descriptor.payload_kind = KSJ_PAYLOAD_KIND_BUFFER_HANDLE;
  descriptor.element_type = KSJ_ELEMENT_TYPE_COMPLEX_FLOAT32;
  descriptor.rank = UINT32_C(2);
  descriptor.dimension_names = ksj_type_registry_complex_image_frame_dimension_names;
  descriptor.layout_flags = KSJ_TYPE_LAYOUT_ROW_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL;
  descriptor.stride_bytes[0U] = ksj_type_registry_complex_image_frame_stride_bytes[0U];
  descriptor.stride_bytes[1U] = ksj_type_registry_complex_image_frame_stride_bytes[1U];
  descriptor.stride_bytes[2U] = ksj_type_registry_complex_image_frame_stride_bytes[2U];
  descriptor.stride_bytes[3U] = ksj_type_registry_complex_image_frame_stride_bytes[3U];
  descriptor.stride_bytes[4U] = ksj_type_registry_complex_image_frame_stride_bytes[4U];
  descriptor.stride_bytes[5U] = ksj_type_registry_complex_image_frame_stride_bytes[5U];
  descriptor.stride_bytes[6U] = ksj_type_registry_complex_image_frame_stride_bytes[6U];
  descriptor.stride_bytes[7U] = ksj_type_registry_complex_image_frame_stride_bytes[7U];
  descriptor.allowed_memory_domains = KSJ_PROVIDER_MEMORY_HOST_PAGEABLE;
  descriptor.minimum_alignment = UINT32_C(64);
  descriptor.mutability = KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH;
  return descriptor;
}

static inline int ksj_type_registry_matches_complex_image_frame(const ksj_type_descriptor_view* descriptor) {
  uint32_t index;
  if (descriptor == NULL || descriptor->type_ref.data == NULL ||
      descriptor->type_ref.size != ksj_type_registry_complex_image_frame_type_ref.size ||
      descriptor->payload_kind != KSJ_PAYLOAD_KIND_BUFFER_HANDLE ||
      descriptor->element_type != KSJ_ELEMENT_TYPE_COMPLEX_FLOAT32 ||
      descriptor->rank != UINT32_C(2) ||
      descriptor->layout_flags != (KSJ_TYPE_LAYOUT_ROW_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL) ||
      descriptor->allowed_memory_domains != (KSJ_PROVIDER_MEMORY_HOST_PAGEABLE) ||
      descriptor->minimum_alignment != UINT32_C(64) ||
      descriptor->mutability != KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH) {
    return 0;
  }
  for (index = UINT32_C(0); index < descriptor->type_ref.size; ++index) {
    if (descriptor->type_ref.data[index] != ksj_type_registry_complex_image_frame_type_ref.data[index]) {
      return 0;
    }
  }
  for (index = UINT32_C(0); index < KSJ_PROVIDER_DIGEST256_SIZE; ++index) {
    if (descriptor->type_identity_digest.bytes[index] != ksj_type_registry_complex_image_frame_identity_digest.bytes[index]) {
      return 0;
    }
  }
  if (descriptor->dimension_names == NULL) {
    return 0;
  }
  for (index = UINT32_C(0); index < UINT32_C(2); ++index) {
    uint64_t character_index;
    if (descriptor->dimension_names[index].data == NULL ||
        descriptor->dimension_names[index].size != ksj_type_registry_complex_image_frame_dimension_names[index].size) {
      return 0;
    }
    for (character_index = UINT64_C(0);
         character_index < descriptor->dimension_names[index].size; ++character_index) {
      if (descriptor->dimension_names[index].data[character_index] != ksj_type_registry_complex_image_frame_dimension_names[index].data[character_index]) {
        return 0;
      }
    }
  }
  for (index = UINT32_C(0); index < UINT32_C(8); ++index) {
    if (descriptor->stride_bytes[index] != ksj_type_registry_complex_image_frame_stride_bytes[index]) {
      return 0;
    }
  }
  return 1;
}

/* ksj.sensitivity-map: One complex spatial coil sensitivity map used by sensitivity-encoded reconstruction or adaptive coil combination. */
/* Structural payload: complex_float32 row_major_contiguous rank 3 [ky, kx, channel]. */
/* Payload semantics: {"completion":"Every image pixel and channel sensitivity required by the calibration key is present before publication.","dimension_meanings":{"channel":"receive_channel_at_pixel","kx":"image_column_from_cartesian_readout_axis","ky":"image_row_from_cartesian_phase_encode_axis"},"numeric_encoding":"little_endian_interleaved_ieee754_binary32_real_imaginary","payload_role":"coil_sensitivity_map"} */
/* Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; calibration keying and sensitivity-map provenance remain control-plane artifacts."} */
static const char ksj_type_registry_sensitivity_map_type_ref_storage[] = "ksj.sensitivity-map";
static const ksj_utf8_view ksj_type_registry_sensitivity_map_type_ref = {
  {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  ksj_type_registry_sensitivity_map_type_ref_storage,
  sizeof(ksj_type_registry_sensitivity_map_type_ref_storage) - 1U
};
static const ksj_utf8_view ksj_type_registry_sensitivity_map_dimension_names[] = {
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "ky",
    sizeof("ky") - 1U
  },
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "kx",
    sizeof("kx") - 1U
  },
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "channel",
    sizeof("channel") - 1U
  },
};
static const uint64_t ksj_type_registry_sensitivity_map_stride_bytes[8] = {
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
};
static const ksj_digest256 ksj_type_registry_sensitivity_map_identity_digest =
{
  {sizeof(ksj_digest256), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  {
    UINT8_C(0x00), UINT8_C(0x7f), UINT8_C(0x17), UINT8_C(0x32), UINT8_C(0xbd), UINT8_C(0x69), UINT8_C(0x3b), UINT8_C(0x87),
    UINT8_C(0xef), UINT8_C(0xa3), UINT8_C(0x33), UINT8_C(0xce), UINT8_C(0x13), UINT8_C(0x79), UINT8_C(0xd0), UINT8_C(0x8e),
    UINT8_C(0x64), UINT8_C(0xbb), UINT8_C(0x24), UINT8_C(0x0e), UINT8_C(0xa3), UINT8_C(0xb8), UINT8_C(0xea), UINT8_C(0xaa),
    UINT8_C(0x67), UINT8_C(0x95), UINT8_C(0x40), UINT8_C(0x61), UINT8_C(0xfd), UINT8_C(0x4b), UINT8_C(0x2c), UINT8_C(0x4d)
  }
}
;

static inline ksj_type_descriptor_view ksj_type_registry_sensitivity_map(void) {
  ksj_type_descriptor_view descriptor = {0};
  descriptor.abi = ksj_provider_abi_header_make((uint32_t)sizeof(descriptor), UINT64_C(0));
  descriptor.type_ref = ksj_type_registry_sensitivity_map_type_ref;
  descriptor.type_identity_digest = ksj_type_registry_sensitivity_map_identity_digest;
  descriptor.payload_kind = KSJ_PAYLOAD_KIND_BUFFER_HANDLE;
  descriptor.element_type = KSJ_ELEMENT_TYPE_COMPLEX_FLOAT32;
  descriptor.rank = UINT32_C(3);
  descriptor.dimension_names = ksj_type_registry_sensitivity_map_dimension_names;
  descriptor.layout_flags = KSJ_TYPE_LAYOUT_ROW_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL;
  descriptor.stride_bytes[0U] = ksj_type_registry_sensitivity_map_stride_bytes[0U];
  descriptor.stride_bytes[1U] = ksj_type_registry_sensitivity_map_stride_bytes[1U];
  descriptor.stride_bytes[2U] = ksj_type_registry_sensitivity_map_stride_bytes[2U];
  descriptor.stride_bytes[3U] = ksj_type_registry_sensitivity_map_stride_bytes[3U];
  descriptor.stride_bytes[4U] = ksj_type_registry_sensitivity_map_stride_bytes[4U];
  descriptor.stride_bytes[5U] = ksj_type_registry_sensitivity_map_stride_bytes[5U];
  descriptor.stride_bytes[6U] = ksj_type_registry_sensitivity_map_stride_bytes[6U];
  descriptor.stride_bytes[7U] = ksj_type_registry_sensitivity_map_stride_bytes[7U];
  descriptor.allowed_memory_domains = KSJ_PROVIDER_MEMORY_HOST_PAGEABLE;
  descriptor.minimum_alignment = UINT32_C(64);
  descriptor.mutability = KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH;
  return descriptor;
}

static inline int ksj_type_registry_matches_sensitivity_map(const ksj_type_descriptor_view* descriptor) {
  uint32_t index;
  if (descriptor == NULL || descriptor->type_ref.data == NULL ||
      descriptor->type_ref.size != ksj_type_registry_sensitivity_map_type_ref.size ||
      descriptor->payload_kind != KSJ_PAYLOAD_KIND_BUFFER_HANDLE ||
      descriptor->element_type != KSJ_ELEMENT_TYPE_COMPLEX_FLOAT32 ||
      descriptor->rank != UINT32_C(3) ||
      descriptor->layout_flags != (KSJ_TYPE_LAYOUT_ROW_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL) ||
      descriptor->allowed_memory_domains != (KSJ_PROVIDER_MEMORY_HOST_PAGEABLE) ||
      descriptor->minimum_alignment != UINT32_C(64) ||
      descriptor->mutability != KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH) {
    return 0;
  }
  for (index = UINT32_C(0); index < descriptor->type_ref.size; ++index) {
    if (descriptor->type_ref.data[index] != ksj_type_registry_sensitivity_map_type_ref.data[index]) {
      return 0;
    }
  }
  for (index = UINT32_C(0); index < KSJ_PROVIDER_DIGEST256_SIZE; ++index) {
    if (descriptor->type_identity_digest.bytes[index] != ksj_type_registry_sensitivity_map_identity_digest.bytes[index]) {
      return 0;
    }
  }
  if (descriptor->dimension_names == NULL) {
    return 0;
  }
  for (index = UINT32_C(0); index < UINT32_C(3); ++index) {
    uint64_t character_index;
    if (descriptor->dimension_names[index].data == NULL ||
        descriptor->dimension_names[index].size != ksj_type_registry_sensitivity_map_dimension_names[index].size) {
      return 0;
    }
    for (character_index = UINT64_C(0);
         character_index < descriptor->dimension_names[index].size; ++character_index) {
      if (descriptor->dimension_names[index].data[character_index] != ksj_type_registry_sensitivity_map_dimension_names[index].data[character_index]) {
        return 0;
      }
    }
  }
  for (index = UINT32_C(0); index < UINT32_C(8); ++index) {
    if (descriptor->stride_bytes[index] != ksj_type_registry_sensitivity_map_stride_bytes[index]) {
      return 0;
    }
  }
  return 1;
}

/* ksj.noncartesian-kspace-frame: One complete multi-channel non-Cartesian k-space sample frame with its trajectory carried on a separate typed port. */
/* Structural payload: complex_float32 channel_major_contiguous rank 2 [channel, sample]. */
/* Payload semantics: {"completion":"All non-Cartesian samples for the logical frame are present before publication.","dimension_meanings":{"channel":"receive_channel","sample":"noncartesian_kspace_sample"},"numeric_encoding":"little_endian_interleaved_ieee754_binary32_real_imaginary","payload_role":"noncartesian_kspace_samples"} */
/* Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; trajectory association and scan metadata remain control-plane artifacts."} */
static const char ksj_type_registry_noncartesian_kspace_frame_type_ref_storage[] = "ksj.noncartesian-kspace-frame";
static const ksj_utf8_view ksj_type_registry_noncartesian_kspace_frame_type_ref = {
  {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  ksj_type_registry_noncartesian_kspace_frame_type_ref_storage,
  sizeof(ksj_type_registry_noncartesian_kspace_frame_type_ref_storage) - 1U
};
static const ksj_utf8_view ksj_type_registry_noncartesian_kspace_frame_dimension_names[] = {
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "channel",
    sizeof("channel") - 1U
  },
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "sample",
    sizeof("sample") - 1U
  },
};
static const uint64_t ksj_type_registry_noncartesian_kspace_frame_stride_bytes[8] = {
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
};
static const ksj_digest256 ksj_type_registry_noncartesian_kspace_frame_identity_digest =
{
  {sizeof(ksj_digest256), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  {
    UINT8_C(0xc9), UINT8_C(0xb8), UINT8_C(0x8d), UINT8_C(0xa9), UINT8_C(0x07), UINT8_C(0x45), UINT8_C(0x03), UINT8_C(0x09),
    UINT8_C(0x6e), UINT8_C(0x68), UINT8_C(0xf8), UINT8_C(0xae), UINT8_C(0xb0), UINT8_C(0x05), UINT8_C(0xfd), UINT8_C(0xcf),
    UINT8_C(0xa9), UINT8_C(0x1e), UINT8_C(0x5d), UINT8_C(0xd6), UINT8_C(0xc2), UINT8_C(0xb9), UINT8_C(0x82), UINT8_C(0x0e),
    UINT8_C(0x02), UINT8_C(0xaf), UINT8_C(0xd5), UINT8_C(0x97), UINT8_C(0x80), UINT8_C(0x7e), UINT8_C(0x08), UINT8_C(0x5d)
  }
}
;

static inline ksj_type_descriptor_view ksj_type_registry_noncartesian_kspace_frame(void) {
  ksj_type_descriptor_view descriptor = {0};
  descriptor.abi = ksj_provider_abi_header_make((uint32_t)sizeof(descriptor), UINT64_C(0));
  descriptor.type_ref = ksj_type_registry_noncartesian_kspace_frame_type_ref;
  descriptor.type_identity_digest = ksj_type_registry_noncartesian_kspace_frame_identity_digest;
  descriptor.payload_kind = KSJ_PAYLOAD_KIND_BUFFER_HANDLE;
  descriptor.element_type = KSJ_ELEMENT_TYPE_COMPLEX_FLOAT32;
  descriptor.rank = UINT32_C(2);
  descriptor.dimension_names = ksj_type_registry_noncartesian_kspace_frame_dimension_names;
  descriptor.layout_flags = KSJ_TYPE_LAYOUT_CHANNEL_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL;
  descriptor.stride_bytes[0U] = ksj_type_registry_noncartesian_kspace_frame_stride_bytes[0U];
  descriptor.stride_bytes[1U] = ksj_type_registry_noncartesian_kspace_frame_stride_bytes[1U];
  descriptor.stride_bytes[2U] = ksj_type_registry_noncartesian_kspace_frame_stride_bytes[2U];
  descriptor.stride_bytes[3U] = ksj_type_registry_noncartesian_kspace_frame_stride_bytes[3U];
  descriptor.stride_bytes[4U] = ksj_type_registry_noncartesian_kspace_frame_stride_bytes[4U];
  descriptor.stride_bytes[5U] = ksj_type_registry_noncartesian_kspace_frame_stride_bytes[5U];
  descriptor.stride_bytes[6U] = ksj_type_registry_noncartesian_kspace_frame_stride_bytes[6U];
  descriptor.stride_bytes[7U] = ksj_type_registry_noncartesian_kspace_frame_stride_bytes[7U];
  descriptor.allowed_memory_domains = KSJ_PROVIDER_MEMORY_HOST_PAGEABLE;
  descriptor.minimum_alignment = UINT32_C(64);
  descriptor.mutability = KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH;
  return descriptor;
}

static inline int ksj_type_registry_matches_noncartesian_kspace_frame(const ksj_type_descriptor_view* descriptor) {
  uint32_t index;
  if (descriptor == NULL || descriptor->type_ref.data == NULL ||
      descriptor->type_ref.size != ksj_type_registry_noncartesian_kspace_frame_type_ref.size ||
      descriptor->payload_kind != KSJ_PAYLOAD_KIND_BUFFER_HANDLE ||
      descriptor->element_type != KSJ_ELEMENT_TYPE_COMPLEX_FLOAT32 ||
      descriptor->rank != UINT32_C(2) ||
      descriptor->layout_flags != (KSJ_TYPE_LAYOUT_CHANNEL_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL) ||
      descriptor->allowed_memory_domains != (KSJ_PROVIDER_MEMORY_HOST_PAGEABLE) ||
      descriptor->minimum_alignment != UINT32_C(64) ||
      descriptor->mutability != KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH) {
    return 0;
  }
  for (index = UINT32_C(0); index < descriptor->type_ref.size; ++index) {
    if (descriptor->type_ref.data[index] != ksj_type_registry_noncartesian_kspace_frame_type_ref.data[index]) {
      return 0;
    }
  }
  for (index = UINT32_C(0); index < KSJ_PROVIDER_DIGEST256_SIZE; ++index) {
    if (descriptor->type_identity_digest.bytes[index] != ksj_type_registry_noncartesian_kspace_frame_identity_digest.bytes[index]) {
      return 0;
    }
  }
  if (descriptor->dimension_names == NULL) {
    return 0;
  }
  for (index = UINT32_C(0); index < UINT32_C(2); ++index) {
    uint64_t character_index;
    if (descriptor->dimension_names[index].data == NULL ||
        descriptor->dimension_names[index].size != ksj_type_registry_noncartesian_kspace_frame_dimension_names[index].size) {
      return 0;
    }
    for (character_index = UINT64_C(0);
         character_index < descriptor->dimension_names[index].size; ++character_index) {
      if (descriptor->dimension_names[index].data[character_index] != ksj_type_registry_noncartesian_kspace_frame_dimension_names[index].data[character_index]) {
        return 0;
      }
    }
  }
  for (index = UINT32_C(0); index < UINT32_C(8); ++index) {
    if (descriptor->stride_bytes[index] != ksj_type_registry_noncartesian_kspace_frame_stride_bytes[index]) {
      return 0;
    }
  }
  return 1;
}

/* ksj.trajectory-frame: One float32 non-Cartesian trajectory frame aligned sample-for-sample with a non-Cartesian k-space frame. */
/* Structural payload: float32 row_major_contiguous rank 2 [sample, coordinate]. */
/* Payload semantics: {"completion":"Every trajectory coordinate for the logical frame's non-Cartesian samples is present before publication.","dimension_meanings":{"coordinate":"trajectory_coordinate","sample":"noncartesian_kspace_sample"},"numeric_encoding":"little_endian_ieee754_binary32","payload_role":"noncartesian_sampling_trajectory"} */
/* Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; trajectory units and scan metadata remain control-plane artifacts."} */
static const char ksj_type_registry_trajectory_frame_type_ref_storage[] = "ksj.trajectory-frame";
static const ksj_utf8_view ksj_type_registry_trajectory_frame_type_ref = {
  {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  ksj_type_registry_trajectory_frame_type_ref_storage,
  sizeof(ksj_type_registry_trajectory_frame_type_ref_storage) - 1U
};
static const ksj_utf8_view ksj_type_registry_trajectory_frame_dimension_names[] = {
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "sample",
    sizeof("sample") - 1U
  },
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "coordinate",
    sizeof("coordinate") - 1U
  },
};
static const uint64_t ksj_type_registry_trajectory_frame_stride_bytes[8] = {
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
};
static const ksj_digest256 ksj_type_registry_trajectory_frame_identity_digest =
{
  {sizeof(ksj_digest256), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  {
    UINT8_C(0x10), UINT8_C(0x50), UINT8_C(0x0d), UINT8_C(0xa9), UINT8_C(0x5c), UINT8_C(0xd0), UINT8_C(0x05), UINT8_C(0xc2),
    UINT8_C(0x37), UINT8_C(0xc3), UINT8_C(0xb5), UINT8_C(0xe8), UINT8_C(0x11), UINT8_C(0x57), UINT8_C(0x38), UINT8_C(0x64),
    UINT8_C(0xce), UINT8_C(0x99), UINT8_C(0x72), UINT8_C(0x9e), UINT8_C(0x41), UINT8_C(0xc1), UINT8_C(0x5e), UINT8_C(0x54),
    UINT8_C(0x69), UINT8_C(0x7c), UINT8_C(0xb4), UINT8_C(0x73), UINT8_C(0xa7), UINT8_C(0x2d), UINT8_C(0x81), UINT8_C(0xe7)
  }
}
;

static inline ksj_type_descriptor_view ksj_type_registry_trajectory_frame(void) {
  ksj_type_descriptor_view descriptor = {0};
  descriptor.abi = ksj_provider_abi_header_make((uint32_t)sizeof(descriptor), UINT64_C(0));
  descriptor.type_ref = ksj_type_registry_trajectory_frame_type_ref;
  descriptor.type_identity_digest = ksj_type_registry_trajectory_frame_identity_digest;
  descriptor.payload_kind = KSJ_PAYLOAD_KIND_BUFFER_HANDLE;
  descriptor.element_type = KSJ_ELEMENT_TYPE_FLOAT32;
  descriptor.rank = UINT32_C(2);
  descriptor.dimension_names = ksj_type_registry_trajectory_frame_dimension_names;
  descriptor.layout_flags = KSJ_TYPE_LAYOUT_ROW_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL;
  descriptor.stride_bytes[0U] = ksj_type_registry_trajectory_frame_stride_bytes[0U];
  descriptor.stride_bytes[1U] = ksj_type_registry_trajectory_frame_stride_bytes[1U];
  descriptor.stride_bytes[2U] = ksj_type_registry_trajectory_frame_stride_bytes[2U];
  descriptor.stride_bytes[3U] = ksj_type_registry_trajectory_frame_stride_bytes[3U];
  descriptor.stride_bytes[4U] = ksj_type_registry_trajectory_frame_stride_bytes[4U];
  descriptor.stride_bytes[5U] = ksj_type_registry_trajectory_frame_stride_bytes[5U];
  descriptor.stride_bytes[6U] = ksj_type_registry_trajectory_frame_stride_bytes[6U];
  descriptor.stride_bytes[7U] = ksj_type_registry_trajectory_frame_stride_bytes[7U];
  descriptor.allowed_memory_domains = KSJ_PROVIDER_MEMORY_HOST_PAGEABLE;
  descriptor.minimum_alignment = UINT32_C(64);
  descriptor.mutability = KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH;
  return descriptor;
}

static inline int ksj_type_registry_matches_trajectory_frame(const ksj_type_descriptor_view* descriptor) {
  uint32_t index;
  if (descriptor == NULL || descriptor->type_ref.data == NULL ||
      descriptor->type_ref.size != ksj_type_registry_trajectory_frame_type_ref.size ||
      descriptor->payload_kind != KSJ_PAYLOAD_KIND_BUFFER_HANDLE ||
      descriptor->element_type != KSJ_ELEMENT_TYPE_FLOAT32 ||
      descriptor->rank != UINT32_C(2) ||
      descriptor->layout_flags != (KSJ_TYPE_LAYOUT_ROW_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL) ||
      descriptor->allowed_memory_domains != (KSJ_PROVIDER_MEMORY_HOST_PAGEABLE) ||
      descriptor->minimum_alignment != UINT32_C(64) ||
      descriptor->mutability != KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH) {
    return 0;
  }
  for (index = UINT32_C(0); index < descriptor->type_ref.size; ++index) {
    if (descriptor->type_ref.data[index] != ksj_type_registry_trajectory_frame_type_ref.data[index]) {
      return 0;
    }
  }
  for (index = UINT32_C(0); index < KSJ_PROVIDER_DIGEST256_SIZE; ++index) {
    if (descriptor->type_identity_digest.bytes[index] != ksj_type_registry_trajectory_frame_identity_digest.bytes[index]) {
      return 0;
    }
  }
  if (descriptor->dimension_names == NULL) {
    return 0;
  }
  for (index = UINT32_C(0); index < UINT32_C(2); ++index) {
    uint64_t character_index;
    if (descriptor->dimension_names[index].data == NULL ||
        descriptor->dimension_names[index].size != ksj_type_registry_trajectory_frame_dimension_names[index].size) {
      return 0;
    }
    for (character_index = UINT64_C(0);
         character_index < descriptor->dimension_names[index].size; ++character_index) {
      if (descriptor->dimension_names[index].data[character_index] != ksj_type_registry_trajectory_frame_dimension_names[index].data[character_index]) {
        return 0;
      }
    }
  }
  for (index = UINT32_C(0); index < UINT32_C(8); ++index) {
    if (descriptor->stride_bytes[index] != ksj_type_registry_trajectory_frame_stride_bytes[index]) {
      return 0;
    }
  }
  return 1;
}

/* ksj.image-frame: One reconstructed two-dimensional float32 scalar image plane used by the implemented Cartesian reconstruction and image-ops operators. */
/* Structural payload: float32 row_major_contiguous rank 2 [ky, kx]. */
/* Payload semantics: {"dimension_meanings":{"kx":"image_column_from_cartesian_readout_axis","ky":"image_row_from_cartesian_phase_encode_axis"},"intensity":"One float32 scalar per output pixel. The Cartesian reconstruction emits finite non-negative magnitudes; later image Operators own any range or non-finite transformation semantics.","numeric_encoding":"little_endian_ieee754_binary32","payload_role":"reconstructed_scalar_image_plane"} */
/* Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; scan and plan metadata remain control-plane artifacts."} */
static const char ksj_type_registry_image_frame_type_ref_storage[] = "ksj.image-frame";
static const ksj_utf8_view ksj_type_registry_image_frame_type_ref = {
  {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  ksj_type_registry_image_frame_type_ref_storage,
  sizeof(ksj_type_registry_image_frame_type_ref_storage) - 1U
};
static const ksj_utf8_view ksj_type_registry_image_frame_dimension_names[] = {
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "ky",
    sizeof("ky") - 1U
  },
  {
    {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
    "kx",
    sizeof("kx") - 1U
  },
};
static const uint64_t ksj_type_registry_image_frame_stride_bytes[8] = {
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
};
static const ksj_digest256 ksj_type_registry_image_frame_identity_digest =
{
  {sizeof(ksj_digest256), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  {
    UINT8_C(0x66), UINT8_C(0xd1), UINT8_C(0x3e), UINT8_C(0xd4), UINT8_C(0x34), UINT8_C(0x07), UINT8_C(0xba), UINT8_C(0x9d),
    UINT8_C(0xd4), UINT8_C(0x49), UINT8_C(0x32), UINT8_C(0x7f), UINT8_C(0x62), UINT8_C(0xa7), UINT8_C(0x52), UINT8_C(0xf8),
    UINT8_C(0x13), UINT8_C(0x7d), UINT8_C(0x32), UINT8_C(0x8b), UINT8_C(0xad), UINT8_C(0x26), UINT8_C(0x20), UINT8_C(0xf5),
    UINT8_C(0x6b), UINT8_C(0x81), UINT8_C(0x7b), UINT8_C(0xf2), UINT8_C(0x14), UINT8_C(0x0b), UINT8_C(0x35), UINT8_C(0x86)
  }
}
;

static inline ksj_type_descriptor_view ksj_type_registry_image_frame(void) {
  ksj_type_descriptor_view descriptor = {0};
  descriptor.abi = ksj_provider_abi_header_make((uint32_t)sizeof(descriptor), UINT64_C(0));
  descriptor.type_ref = ksj_type_registry_image_frame_type_ref;
  descriptor.type_identity_digest = ksj_type_registry_image_frame_identity_digest;
  descriptor.payload_kind = KSJ_PAYLOAD_KIND_BUFFER_HANDLE;
  descriptor.element_type = KSJ_ELEMENT_TYPE_FLOAT32;
  descriptor.rank = UINT32_C(2);
  descriptor.dimension_names = ksj_type_registry_image_frame_dimension_names;
  descriptor.layout_flags = KSJ_TYPE_LAYOUT_ROW_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL;
  descriptor.stride_bytes[0U] = ksj_type_registry_image_frame_stride_bytes[0U];
  descriptor.stride_bytes[1U] = ksj_type_registry_image_frame_stride_bytes[1U];
  descriptor.stride_bytes[2U] = ksj_type_registry_image_frame_stride_bytes[2U];
  descriptor.stride_bytes[3U] = ksj_type_registry_image_frame_stride_bytes[3U];
  descriptor.stride_bytes[4U] = ksj_type_registry_image_frame_stride_bytes[4U];
  descriptor.stride_bytes[5U] = ksj_type_registry_image_frame_stride_bytes[5U];
  descriptor.stride_bytes[6U] = ksj_type_registry_image_frame_stride_bytes[6U];
  descriptor.stride_bytes[7U] = ksj_type_registry_image_frame_stride_bytes[7U];
  descriptor.allowed_memory_domains = KSJ_PROVIDER_MEMORY_HOST_PAGEABLE;
  descriptor.minimum_alignment = UINT32_C(64);
  descriptor.mutability = KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH;
  return descriptor;
}

static inline int ksj_type_registry_matches_image_frame(const ksj_type_descriptor_view* descriptor) {
  uint32_t index;
  if (descriptor == NULL || descriptor->type_ref.data == NULL ||
      descriptor->type_ref.size != ksj_type_registry_image_frame_type_ref.size ||
      descriptor->payload_kind != KSJ_PAYLOAD_KIND_BUFFER_HANDLE ||
      descriptor->element_type != KSJ_ELEMENT_TYPE_FLOAT32 ||
      descriptor->rank != UINT32_C(2) ||
      descriptor->layout_flags != (KSJ_TYPE_LAYOUT_ROW_MAJOR_CONTIGUOUS | KSJ_TYPE_STRIDES_CANONICAL) ||
      descriptor->allowed_memory_domains != (KSJ_PROVIDER_MEMORY_HOST_PAGEABLE) ||
      descriptor->minimum_alignment != UINT32_C(64) ||
      descriptor->mutability != KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH) {
    return 0;
  }
  for (index = UINT32_C(0); index < descriptor->type_ref.size; ++index) {
    if (descriptor->type_ref.data[index] != ksj_type_registry_image_frame_type_ref.data[index]) {
      return 0;
    }
  }
  for (index = UINT32_C(0); index < KSJ_PROVIDER_DIGEST256_SIZE; ++index) {
    if (descriptor->type_identity_digest.bytes[index] != ksj_type_registry_image_frame_identity_digest.bytes[index]) {
      return 0;
    }
  }
  if (descriptor->dimension_names == NULL) {
    return 0;
  }
  for (index = UINT32_C(0); index < UINT32_C(2); ++index) {
    uint64_t character_index;
    if (descriptor->dimension_names[index].data == NULL ||
        descriptor->dimension_names[index].size != ksj_type_registry_image_frame_dimension_names[index].size) {
      return 0;
    }
    for (character_index = UINT64_C(0);
         character_index < descriptor->dimension_names[index].size; ++character_index) {
      if (descriptor->dimension_names[index].data[character_index] != ksj_type_registry_image_frame_dimension_names[index].data[character_index]) {
        return 0;
      }
    }
  }
  for (index = UINT32_C(0); index < UINT32_C(8); ++index) {
    if (descriptor->stride_bytes[index] != ksj_type_registry_image_frame_stride_bytes[index]) {
      return 0;
    }
  }
  return 1;
}

/* ksj.control-message: One immutable host-resident opaque control or diagnostic message envelope for generic public-adapter and control-plane graph ports. */
/* Structural payload: none opaque rank 0 []. */
/* Payload semantics: {"dimension_meanings":{},"message_contract":"The handle denotes one complete immutable host-resident control or diagnostic envelope. Its payload representation, ownership details, and internal fields are opaque to generic graph adapters; only this TypeRef establishes compatibility.","numeric_encoding":"opaque_provider_defined_message_handle","payload_role":"opaque_control_or_diagnostic_message_envelope"} */
/* Metadata semantics: {"kind":"none","meaning":"No separately-addressable metadata bytes are defined. Any message details travel inside the opaque handle under its owning component's contract."} */
static const char ksj_type_registry_control_message_type_ref_storage[] = "ksj.control-message";
static const ksj_utf8_view ksj_type_registry_control_message_type_ref = {
  {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  ksj_type_registry_control_message_type_ref_storage,
  sizeof(ksj_type_registry_control_message_type_ref_storage) - 1U
};
static const uint64_t ksj_type_registry_control_message_stride_bytes[8] = {
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
};
static const ksj_digest256 ksj_type_registry_control_message_identity_digest =
{
  {sizeof(ksj_digest256), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  {
    UINT8_C(0x63), UINT8_C(0x72), UINT8_C(0x70), UINT8_C(0x83), UINT8_C(0xde), UINT8_C(0x1a), UINT8_C(0xb6), UINT8_C(0x91),
    UINT8_C(0x5f), UINT8_C(0xfe), UINT8_C(0x5b), UINT8_C(0x4d), UINT8_C(0xbe), UINT8_C(0xbe), UINT8_C(0xdf), UINT8_C(0xda),
    UINT8_C(0x20), UINT8_C(0x7f), UINT8_C(0x61), UINT8_C(0xa9), UINT8_C(0xe8), UINT8_C(0xb7), UINT8_C(0xfd), UINT8_C(0xf9),
    UINT8_C(0xc8), UINT8_C(0xe7), UINT8_C(0x96), UINT8_C(0xa5), UINT8_C(0xb3), UINT8_C(0x8f), UINT8_C(0x8f), UINT8_C(0x91)
  }
}
;

static inline ksj_type_descriptor_view ksj_type_registry_control_message(void) {
  ksj_type_descriptor_view descriptor = {0};
  descriptor.abi = ksj_provider_abi_header_make((uint32_t)sizeof(descriptor), UINT64_C(0));
  descriptor.type_ref = ksj_type_registry_control_message_type_ref;
  descriptor.type_identity_digest = ksj_type_registry_control_message_identity_digest;
  descriptor.payload_kind = KSJ_PAYLOAD_KIND_MESSAGE_HANDLE;
  descriptor.element_type = KSJ_ELEMENT_TYPE_NONE;
  descriptor.rank = UINT32_C(0);
  descriptor.layout_flags = KSJ_TYPE_LAYOUT_OPAQUE | KSJ_TYPE_STRIDES_CANONICAL;
  descriptor.stride_bytes[0U] = ksj_type_registry_control_message_stride_bytes[0U];
  descriptor.stride_bytes[1U] = ksj_type_registry_control_message_stride_bytes[1U];
  descriptor.stride_bytes[2U] = ksj_type_registry_control_message_stride_bytes[2U];
  descriptor.stride_bytes[3U] = ksj_type_registry_control_message_stride_bytes[3U];
  descriptor.stride_bytes[4U] = ksj_type_registry_control_message_stride_bytes[4U];
  descriptor.stride_bytes[5U] = ksj_type_registry_control_message_stride_bytes[5U];
  descriptor.stride_bytes[6U] = ksj_type_registry_control_message_stride_bytes[6U];
  descriptor.stride_bytes[7U] = ksj_type_registry_control_message_stride_bytes[7U];
  descriptor.allowed_memory_domains = KSJ_PROVIDER_MEMORY_HOST_PAGEABLE;
  descriptor.minimum_alignment = UINT32_C(8);
  descriptor.mutability = KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH;
  return descriptor;
}

static inline int ksj_type_registry_matches_control_message(const ksj_type_descriptor_view* descriptor) {
  uint32_t index;
  if (descriptor == NULL || descriptor->type_ref.data == NULL ||
      descriptor->type_ref.size != ksj_type_registry_control_message_type_ref.size ||
      descriptor->payload_kind != KSJ_PAYLOAD_KIND_MESSAGE_HANDLE ||
      descriptor->element_type != KSJ_ELEMENT_TYPE_NONE ||
      descriptor->rank != UINT32_C(0) ||
      descriptor->layout_flags != (KSJ_TYPE_LAYOUT_OPAQUE | KSJ_TYPE_STRIDES_CANONICAL) ||
      descriptor->allowed_memory_domains != (KSJ_PROVIDER_MEMORY_HOST_PAGEABLE) ||
      descriptor->minimum_alignment != UINT32_C(8) ||
      descriptor->mutability != KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH) {
    return 0;
  }
  for (index = UINT32_C(0); index < descriptor->type_ref.size; ++index) {
    if (descriptor->type_ref.data[index] != ksj_type_registry_control_message_type_ref.data[index]) {
      return 0;
    }
  }
  for (index = UINT32_C(0); index < KSJ_PROVIDER_DIGEST256_SIZE; ++index) {
    if (descriptor->type_identity_digest.bytes[index] != ksj_type_registry_control_message_identity_digest.bytes[index]) {
      return 0;
    }
  }
  for (index = UINT32_C(0); index < UINT32_C(8); ++index) {
    if (descriptor->stride_bytes[index] != ksj_type_registry_control_message_stride_bytes[index]) {
      return 0;
    }
  }
  return 1;
}

/* ismrmrd.acquisition: One immutable host-resident opaque ISMRMRD acquisition message envelope accepted at a declared PipelineDefinition ingress. */
/* Structural payload: none opaque rank 0 []. */
/* Payload semantics: {"dimension_meanings":{},"message_contract":"The handle denotes one complete ISMRMRD acquisition envelope, including its acquisition header and any sample or trajectory payload owned by the ISMRMRD binding. Generic graph code neither decodes nor retains internal fields outside the owning message-handle contract.","numeric_encoding":"opaque_ismrmrd_acquisition_message_handle","payload_role":"ismrmrd_acquisition_message_envelope"} */
/* Metadata semantics: {"kind":"none","meaning":"No separately-addressable metadata bytes are defined. ISMRMRD acquisition header and attribute semantics remain inside the opaque message handle."} */
static const char ksj_type_registry_ismrmrd_acquisition_type_ref_storage[] = "ismrmrd.acquisition";
static const ksj_utf8_view ksj_type_registry_ismrmrd_acquisition_type_ref = {
  {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  ksj_type_registry_ismrmrd_acquisition_type_ref_storage,
  sizeof(ksj_type_registry_ismrmrd_acquisition_type_ref_storage) - 1U
};
static const uint64_t ksj_type_registry_ismrmrd_acquisition_stride_bytes[8] = {
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
};
static const ksj_digest256 ksj_type_registry_ismrmrd_acquisition_identity_digest =
{
  {sizeof(ksj_digest256), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  {
    UINT8_C(0xc4), UINT8_C(0x65), UINT8_C(0xcb), UINT8_C(0xdd), UINT8_C(0x31), UINT8_C(0x19), UINT8_C(0xa3), UINT8_C(0x0e),
    UINT8_C(0x99), UINT8_C(0x1e), UINT8_C(0x3a), UINT8_C(0x60), UINT8_C(0x8d), UINT8_C(0x38), UINT8_C(0x1a), UINT8_C(0x44),
    UINT8_C(0x83), UINT8_C(0x3d), UINT8_C(0x5b), UINT8_C(0x6d), UINT8_C(0xdb), UINT8_C(0x14), UINT8_C(0x8f), UINT8_C(0x55),
    UINT8_C(0x12), UINT8_C(0x0b), UINT8_C(0x88), UINT8_C(0x0a), UINT8_C(0xf3), UINT8_C(0xa4), UINT8_C(0xd9), UINT8_C(0x9b)
  }
}
;

static inline ksj_type_descriptor_view ksj_type_registry_ismrmrd_acquisition(void) {
  ksj_type_descriptor_view descriptor = {0};
  descriptor.abi = ksj_provider_abi_header_make((uint32_t)sizeof(descriptor), UINT64_C(0));
  descriptor.type_ref = ksj_type_registry_ismrmrd_acquisition_type_ref;
  descriptor.type_identity_digest = ksj_type_registry_ismrmrd_acquisition_identity_digest;
  descriptor.payload_kind = KSJ_PAYLOAD_KIND_MESSAGE_HANDLE;
  descriptor.element_type = KSJ_ELEMENT_TYPE_NONE;
  descriptor.rank = UINT32_C(0);
  descriptor.layout_flags = KSJ_TYPE_LAYOUT_OPAQUE | KSJ_TYPE_STRIDES_CANONICAL;
  descriptor.stride_bytes[0U] = ksj_type_registry_ismrmrd_acquisition_stride_bytes[0U];
  descriptor.stride_bytes[1U] = ksj_type_registry_ismrmrd_acquisition_stride_bytes[1U];
  descriptor.stride_bytes[2U] = ksj_type_registry_ismrmrd_acquisition_stride_bytes[2U];
  descriptor.stride_bytes[3U] = ksj_type_registry_ismrmrd_acquisition_stride_bytes[3U];
  descriptor.stride_bytes[4U] = ksj_type_registry_ismrmrd_acquisition_stride_bytes[4U];
  descriptor.stride_bytes[5U] = ksj_type_registry_ismrmrd_acquisition_stride_bytes[5U];
  descriptor.stride_bytes[6U] = ksj_type_registry_ismrmrd_acquisition_stride_bytes[6U];
  descriptor.stride_bytes[7U] = ksj_type_registry_ismrmrd_acquisition_stride_bytes[7U];
  descriptor.allowed_memory_domains = KSJ_PROVIDER_MEMORY_HOST_PAGEABLE;
  descriptor.minimum_alignment = UINT32_C(8);
  descriptor.mutability = KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH;
  return descriptor;
}

static inline int ksj_type_registry_matches_ismrmrd_acquisition(const ksj_type_descriptor_view* descriptor) {
  uint32_t index;
  if (descriptor == NULL || descriptor->type_ref.data == NULL ||
      descriptor->type_ref.size != ksj_type_registry_ismrmrd_acquisition_type_ref.size ||
      descriptor->payload_kind != KSJ_PAYLOAD_KIND_MESSAGE_HANDLE ||
      descriptor->element_type != KSJ_ELEMENT_TYPE_NONE ||
      descriptor->rank != UINT32_C(0) ||
      descriptor->layout_flags != (KSJ_TYPE_LAYOUT_OPAQUE | KSJ_TYPE_STRIDES_CANONICAL) ||
      descriptor->allowed_memory_domains != (KSJ_PROVIDER_MEMORY_HOST_PAGEABLE) ||
      descriptor->minimum_alignment != UINT32_C(8) ||
      descriptor->mutability != KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH) {
    return 0;
  }
  for (index = UINT32_C(0); index < descriptor->type_ref.size; ++index) {
    if (descriptor->type_ref.data[index] != ksj_type_registry_ismrmrd_acquisition_type_ref.data[index]) {
      return 0;
    }
  }
  for (index = UINT32_C(0); index < KSJ_PROVIDER_DIGEST256_SIZE; ++index) {
    if (descriptor->type_identity_digest.bytes[index] != ksj_type_registry_ismrmrd_acquisition_identity_digest.bytes[index]) {
      return 0;
    }
  }
  for (index = UINT32_C(0); index < UINT32_C(8); ++index) {
    if (descriptor->stride_bytes[index] != ksj_type_registry_ismrmrd_acquisition_stride_bytes[index]) {
      return 0;
    }
  }
  return 1;
}

/* ismrmrd.waveform: One immutable host-resident opaque ISMRMRD waveform message envelope accepted at a declared PipelineDefinition ingress. */
/* Structural payload: none opaque rank 0 []. */
/* Payload semantics: {"dimension_meanings":{},"message_contract":"The handle denotes one complete ISMRMRD waveform envelope, including its waveform header and waveform data owned by the ISMRMRD binding. Generic graph code neither decodes nor retains internal fields outside the owning message-handle contract.","numeric_encoding":"opaque_ismrmrd_waveform_message_handle","payload_role":"ismrmrd_waveform_message_envelope"} */
/* Metadata semantics: {"kind":"none","meaning":"No separately-addressable metadata bytes are defined. ISMRMRD waveform header and sample semantics remain inside the opaque message handle."} */
static const char ksj_type_registry_ismrmrd_waveform_type_ref_storage[] = "ismrmrd.waveform";
static const ksj_utf8_view ksj_type_registry_ismrmrd_waveform_type_ref = {
  {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  ksj_type_registry_ismrmrd_waveform_type_ref_storage,
  sizeof(ksj_type_registry_ismrmrd_waveform_type_ref_storage) - 1U
};
static const uint64_t ksj_type_registry_ismrmrd_waveform_stride_bytes[8] = {
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
};
static const ksj_digest256 ksj_type_registry_ismrmrd_waveform_identity_digest =
{
  {sizeof(ksj_digest256), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  {
    UINT8_C(0xcf), UINT8_C(0x31), UINT8_C(0x7a), UINT8_C(0x25), UINT8_C(0x80), UINT8_C(0x2a), UINT8_C(0xf2), UINT8_C(0x03),
    UINT8_C(0x2a), UINT8_C(0xb9), UINT8_C(0x44), UINT8_C(0xc8), UINT8_C(0x1e), UINT8_C(0xb6), UINT8_C(0xf6), UINT8_C(0xc8),
    UINT8_C(0x52), UINT8_C(0x78), UINT8_C(0x22), UINT8_C(0x98), UINT8_C(0x47), UINT8_C(0x04), UINT8_C(0xc2), UINT8_C(0x0e),
    UINT8_C(0x74), UINT8_C(0x2e), UINT8_C(0x1c), UINT8_C(0xb4), UINT8_C(0xb7), UINT8_C(0x5f), UINT8_C(0x16), UINT8_C(0x96)
  }
}
;

static inline ksj_type_descriptor_view ksj_type_registry_ismrmrd_waveform(void) {
  ksj_type_descriptor_view descriptor = {0};
  descriptor.abi = ksj_provider_abi_header_make((uint32_t)sizeof(descriptor), UINT64_C(0));
  descriptor.type_ref = ksj_type_registry_ismrmrd_waveform_type_ref;
  descriptor.type_identity_digest = ksj_type_registry_ismrmrd_waveform_identity_digest;
  descriptor.payload_kind = KSJ_PAYLOAD_KIND_MESSAGE_HANDLE;
  descriptor.element_type = KSJ_ELEMENT_TYPE_NONE;
  descriptor.rank = UINT32_C(0);
  descriptor.layout_flags = KSJ_TYPE_LAYOUT_OPAQUE | KSJ_TYPE_STRIDES_CANONICAL;
  descriptor.stride_bytes[0U] = ksj_type_registry_ismrmrd_waveform_stride_bytes[0U];
  descriptor.stride_bytes[1U] = ksj_type_registry_ismrmrd_waveform_stride_bytes[1U];
  descriptor.stride_bytes[2U] = ksj_type_registry_ismrmrd_waveform_stride_bytes[2U];
  descriptor.stride_bytes[3U] = ksj_type_registry_ismrmrd_waveform_stride_bytes[3U];
  descriptor.stride_bytes[4U] = ksj_type_registry_ismrmrd_waveform_stride_bytes[4U];
  descriptor.stride_bytes[5U] = ksj_type_registry_ismrmrd_waveform_stride_bytes[5U];
  descriptor.stride_bytes[6U] = ksj_type_registry_ismrmrd_waveform_stride_bytes[6U];
  descriptor.stride_bytes[7U] = ksj_type_registry_ismrmrd_waveform_stride_bytes[7U];
  descriptor.allowed_memory_domains = KSJ_PROVIDER_MEMORY_HOST_PAGEABLE;
  descriptor.minimum_alignment = UINT32_C(8);
  descriptor.mutability = KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH;
  return descriptor;
}

static inline int ksj_type_registry_matches_ismrmrd_waveform(const ksj_type_descriptor_view* descriptor) {
  uint32_t index;
  if (descriptor == NULL || descriptor->type_ref.data == NULL ||
      descriptor->type_ref.size != ksj_type_registry_ismrmrd_waveform_type_ref.size ||
      descriptor->payload_kind != KSJ_PAYLOAD_KIND_MESSAGE_HANDLE ||
      descriptor->element_type != KSJ_ELEMENT_TYPE_NONE ||
      descriptor->rank != UINT32_C(0) ||
      descriptor->layout_flags != (KSJ_TYPE_LAYOUT_OPAQUE | KSJ_TYPE_STRIDES_CANONICAL) ||
      descriptor->allowed_memory_domains != (KSJ_PROVIDER_MEMORY_HOST_PAGEABLE) ||
      descriptor->minimum_alignment != UINT32_C(8) ||
      descriptor->mutability != KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH) {
    return 0;
  }
  for (index = UINT32_C(0); index < descriptor->type_ref.size; ++index) {
    if (descriptor->type_ref.data[index] != ksj_type_registry_ismrmrd_waveform_type_ref.data[index]) {
      return 0;
    }
  }
  for (index = UINT32_C(0); index < KSJ_PROVIDER_DIGEST256_SIZE; ++index) {
    if (descriptor->type_identity_digest.bytes[index] != ksj_type_registry_ismrmrd_waveform_identity_digest.bytes[index]) {
      return 0;
    }
  }
  for (index = UINT32_C(0); index < UINT32_C(8); ++index) {
    if (descriptor->stride_bytes[index] != ksj_type_registry_ismrmrd_waveform_stride_bytes[index]) {
      return 0;
    }
  }
  return 1;
}

/* ismrmrd.image: One immutable host-resident opaque ISMRMRD image message envelope accepted at a declared PipelineDefinition egress. */
/* Structural payload: none opaque rank 0 []. */
/* Payload semantics: {"dimension_meanings":{},"message_contract":"The handle denotes one complete ISMRMRD image envelope, including its image header, pixels, and attributes owned by the ISMRMRD binding. Generic graph code neither decodes nor retains internal fields outside the owning message-handle contract.","numeric_encoding":"opaque_ismrmrd_image_message_handle","payload_role":"ismrmrd_image_message_envelope"} */
/* Metadata semantics: {"kind":"none","meaning":"No separately-addressable metadata bytes are defined. ISMRMRD image header, pixel, and attribute semantics remain inside the opaque message handle."} */
static const char ksj_type_registry_ismrmrd_image_type_ref_storage[] = "ismrmrd.image";
static const ksj_utf8_view ksj_type_registry_ismrmrd_image_type_ref = {
  {sizeof(ksj_utf8_view), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  ksj_type_registry_ismrmrd_image_type_ref_storage,
  sizeof(ksj_type_registry_ismrmrd_image_type_ref_storage) - 1U
};
static const uint64_t ksj_type_registry_ismrmrd_image_stride_bytes[8] = {
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
  UINT64_C(0),
};
static const ksj_digest256 ksj_type_registry_ismrmrd_image_identity_digest =
{
  {sizeof(ksj_digest256), UINT32_C(0), UINT64_C(0), {UINT64_C(0), UINT64_C(0)}},
  {
    UINT8_C(0xff), UINT8_C(0x79), UINT8_C(0xd7), UINT8_C(0xb1), UINT8_C(0x00), UINT8_C(0xe9), UINT8_C(0x3e), UINT8_C(0x57),
    UINT8_C(0xc6), UINT8_C(0x28), UINT8_C(0xd0), UINT8_C(0xe4), UINT8_C(0xf2), UINT8_C(0x5d), UINT8_C(0x3d), UINT8_C(0x0f),
    UINT8_C(0xbd), UINT8_C(0x7d), UINT8_C(0x5f), UINT8_C(0xd5), UINT8_C(0x6f), UINT8_C(0x36), UINT8_C(0x3a), UINT8_C(0x70),
    UINT8_C(0x25), UINT8_C(0x9a), UINT8_C(0x96), UINT8_C(0x05), UINT8_C(0x4a), UINT8_C(0x90), UINT8_C(0x1e), UINT8_C(0xf9)
  }
}
;

static inline ksj_type_descriptor_view ksj_type_registry_ismrmrd_image(void) {
  ksj_type_descriptor_view descriptor = {0};
  descriptor.abi = ksj_provider_abi_header_make((uint32_t)sizeof(descriptor), UINT64_C(0));
  descriptor.type_ref = ksj_type_registry_ismrmrd_image_type_ref;
  descriptor.type_identity_digest = ksj_type_registry_ismrmrd_image_identity_digest;
  descriptor.payload_kind = KSJ_PAYLOAD_KIND_MESSAGE_HANDLE;
  descriptor.element_type = KSJ_ELEMENT_TYPE_NONE;
  descriptor.rank = UINT32_C(0);
  descriptor.layout_flags = KSJ_TYPE_LAYOUT_OPAQUE | KSJ_TYPE_STRIDES_CANONICAL;
  descriptor.stride_bytes[0U] = ksj_type_registry_ismrmrd_image_stride_bytes[0U];
  descriptor.stride_bytes[1U] = ksj_type_registry_ismrmrd_image_stride_bytes[1U];
  descriptor.stride_bytes[2U] = ksj_type_registry_ismrmrd_image_stride_bytes[2U];
  descriptor.stride_bytes[3U] = ksj_type_registry_ismrmrd_image_stride_bytes[3U];
  descriptor.stride_bytes[4U] = ksj_type_registry_ismrmrd_image_stride_bytes[4U];
  descriptor.stride_bytes[5U] = ksj_type_registry_ismrmrd_image_stride_bytes[5U];
  descriptor.stride_bytes[6U] = ksj_type_registry_ismrmrd_image_stride_bytes[6U];
  descriptor.stride_bytes[7U] = ksj_type_registry_ismrmrd_image_stride_bytes[7U];
  descriptor.allowed_memory_domains = KSJ_PROVIDER_MEMORY_HOST_PAGEABLE;
  descriptor.minimum_alignment = UINT32_C(8);
  descriptor.mutability = KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH;
  return descriptor;
}

static inline int ksj_type_registry_matches_ismrmrd_image(const ksj_type_descriptor_view* descriptor) {
  uint32_t index;
  if (descriptor == NULL || descriptor->type_ref.data == NULL ||
      descriptor->type_ref.size != ksj_type_registry_ismrmrd_image_type_ref.size ||
      descriptor->payload_kind != KSJ_PAYLOAD_KIND_MESSAGE_HANDLE ||
      descriptor->element_type != KSJ_ELEMENT_TYPE_NONE ||
      descriptor->rank != UINT32_C(0) ||
      descriptor->layout_flags != (KSJ_TYPE_LAYOUT_OPAQUE | KSJ_TYPE_STRIDES_CANONICAL) ||
      descriptor->allowed_memory_domains != (KSJ_PROVIDER_MEMORY_HOST_PAGEABLE) ||
      descriptor->minimum_alignment != UINT32_C(8) ||
      descriptor->mutability != KSJ_PAYLOAD_MUTABILITY_IMMUTABLE_AFTER_PUBLISH) {
    return 0;
  }
  for (index = UINT32_C(0); index < descriptor->type_ref.size; ++index) {
    if (descriptor->type_ref.data[index] != ksj_type_registry_ismrmrd_image_type_ref.data[index]) {
      return 0;
    }
  }
  for (index = UINT32_C(0); index < KSJ_PROVIDER_DIGEST256_SIZE; ++index) {
    if (descriptor->type_identity_digest.bytes[index] != ksj_type_registry_ismrmrd_image_identity_digest.bytes[index]) {
      return 0;
    }
  }
  for (index = UINT32_C(0); index < UINT32_C(8); ++index) {
    if (descriptor->stride_bytes[index] != ksj_type_registry_ismrmrd_image_stride_bytes[index]) {
      return 0;
    }
  }
  return 1;
}

// clang-format on

#endif /* KSPACEJET_PROVIDER_TYPE_REGISTRY_H_ */
