// Generated by tools/type_registry/generate.py from types/registry.json. DO NOT EDIT.
// Type identities are derived from the canonical structural descriptor; a semantic change needs a distinct TypeRef.
#pragma once

#include "kspacejet/recon/type_descriptor.hpp"

#include <string>
#include <string_view>

namespace ksj::recon::types {

// clang-format off

// ksj.kspace-frame: One complete multi-channel Cartesian k-space frame for reconstruction and k-space conditioning operators.
// Structural payload: complex_float32 channel_major_contiguous rank 3 [channel, ky, kx].
// Payload semantics: {"completion":"All declared ky lines for the logical frame are present before publication.","dimension_meanings":{"channel":"receive_channel","kx":"cartesian_readout_sample","ky":"cartesian_phase_encode_line"},"numeric_encoding":"little_endian_interleaved_ieee754_binary32_real_imaginary","payload_role":"complete_cartesian_kspace_frame"}
// Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; scan and plan metadata remain control-plane artifacts."}
inline constexpr std::string_view kKspaceFrameTypeRef = "ksj.kspace-frame";

[[nodiscard]] inline Result<TypeDescriptor> kspace_frame() {
  TypeDescriptorSpec specification;
  specification.type_ref = std::string(kKspaceFrameTypeRef);
  specification.payload_kind = PayloadKind::buffer_handle;
  specification.element_type = ElementType::complex_float32;
  specification.rank = 3U;
  specification.dimensions = {"channel", "ky", "kx"};
  specification.layout = LayoutKind::channel_major_contiguous;
  specification.strides = StrideKind::canonical;
  specification.explicit_byte_strides = {};
  specification.allowed_memory_domains = {TypeMemoryDomain::host_normal};
  specification.min_alignment_bytes = 64U;
  specification.mutability = PayloadMutability::immutable_after_publish;
  return TypeDescriptor::create(specification);
}

// ksj.noise-calibration-frame: One multi-channel complex noise-only calibration sample frame used to estimate a noise model.
// Structural payload: complex_float32 channel_major_contiguous rank 2 [channel, sample].
// Payload semantics: {"completion":"All samples belonging to one noise-calibration frame are present before publication.","dimension_meanings":{"channel":"physical_receive_channel","sample":"noise_only_readout_sample"},"numeric_encoding":"little_endian_interleaved_ieee754_binary32_real_imaginary","payload_role":"noise_calibration_samples"}
// Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; calibration keying and scan metadata remain control-plane artifacts."}
inline constexpr std::string_view kNoiseCalibrationFrameTypeRef = "ksj.noise-calibration-frame";

[[nodiscard]] inline Result<TypeDescriptor> noise_calibration_frame() {
  TypeDescriptorSpec specification;
  specification.type_ref = std::string(kNoiseCalibrationFrameTypeRef);
  specification.payload_kind = PayloadKind::buffer_handle;
  specification.element_type = ElementType::complex_float32;
  specification.rank = 2U;
  specification.dimensions = {"channel", "sample"};
  specification.layout = LayoutKind::channel_major_contiguous;
  specification.strides = StrideKind::canonical;
  specification.explicit_byte_strides = {};
  specification.allowed_memory_domains = {TypeMemoryDomain::host_normal};
  specification.min_alignment_bytes = 64U;
  specification.mutability = PayloadMutability::immutable_after_publish;
  return TypeDescriptor::create(specification);
}

// ksj.noise-model: One complex channel-domain noise whitening model produced from noise calibration data.
// Structural payload: complex_float32 row_major_contiguous rank 2 [output_channel, input_channel].
// Payload semantics: {"completion":"The matrix completely defines the immutable whitening transform for its calibration key.","dimension_meanings":{"input_channel":"physical_receive_channel","output_channel":"whitened_receive_channel"},"numeric_encoding":"little_endian_interleaved_ieee754_binary32_real_imaginary","payload_role":"noise_whitening_matrix"}
// Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; calibration keying and model provenance remain control-plane artifacts."}
inline constexpr std::string_view kNoiseModelTypeRef = "ksj.noise-model";

[[nodiscard]] inline Result<TypeDescriptor> noise_model() {
  TypeDescriptorSpec specification;
  specification.type_ref = std::string(kNoiseModelTypeRef);
  specification.payload_kind = PayloadKind::buffer_handle;
  specification.element_type = ElementType::complex_float32;
  specification.rank = 2U;
  specification.dimensions = {"output_channel", "input_channel"};
  specification.layout = LayoutKind::row_major_contiguous;
  specification.strides = StrideKind::canonical;
  specification.explicit_byte_strides = {};
  specification.allowed_memory_domains = {TypeMemoryDomain::host_normal};
  specification.min_alignment_bytes = 64U;
  specification.mutability = PayloadMutability::immutable_after_publish;
  return TypeDescriptor::create(specification);
}

// ksj.phase-reference-frame: One multi-channel complex Cartesian phase-reference frame used to estimate phase correction.
// Structural payload: complex_float32 channel_major_contiguous rank 3 [channel, reference_line, kx].
// Payload semantics: {"completion":"All declared phase-reference lines for the logical frame are present before publication.","dimension_meanings":{"channel":"physical_receive_channel","kx":"cartesian_readout_sample","reference_line":"phase_reference_line"},"numeric_encoding":"little_endian_interleaved_ieee754_binary32_real_imaginary","payload_role":"phase_reference_kspace_frame"}
// Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; phase-reference classification and keying remain control-plane artifacts."}
inline constexpr std::string_view kPhaseReferenceFrameTypeRef = "ksj.phase-reference-frame";

[[nodiscard]] inline Result<TypeDescriptor> phase_reference_frame() {
  TypeDescriptorSpec specification;
  specification.type_ref = std::string(kPhaseReferenceFrameTypeRef);
  specification.payload_kind = PayloadKind::buffer_handle;
  specification.element_type = ElementType::complex_float32;
  specification.rank = 3U;
  specification.dimensions = {"channel", "reference_line", "kx"};
  specification.layout = LayoutKind::channel_major_contiguous;
  specification.strides = StrideKind::canonical;
  specification.explicit_byte_strides = {};
  specification.allowed_memory_domains = {TypeMemoryDomain::host_normal};
  specification.min_alignment_bytes = 64U;
  specification.mutability = PayloadMutability::immutable_after_publish;
  return TypeDescriptor::create(specification);
}

// ksj.phase-model: One complex channel-by-readout phase correction model produced from phase-reference data.
// Structural payload: complex_float32 channel_major_contiguous rank 2 [channel, kx].
// Payload semantics: {"completion":"The phasor covers every receive channel and readout sample required by its calibration key.","dimension_meanings":{"channel":"physical_receive_channel","kx":"cartesian_readout_sample"},"numeric_encoding":"little_endian_interleaved_ieee754_binary32_real_imaginary","payload_role":"phase_correction_phasor"}
// Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; calibration keying and model provenance remain control-plane artifacts."}
inline constexpr std::string_view kPhaseModelTypeRef = "ksj.phase-model";

[[nodiscard]] inline Result<TypeDescriptor> phase_model() {
  TypeDescriptorSpec specification;
  specification.type_ref = std::string(kPhaseModelTypeRef);
  specification.payload_kind = PayloadKind::buffer_handle;
  specification.element_type = ElementType::complex_float32;
  specification.rank = 2U;
  specification.dimensions = {"channel", "kx"};
  specification.layout = LayoutKind::channel_major_contiguous;
  specification.strides = StrideKind::canonical;
  specification.explicit_byte_strides = {};
  specification.allowed_memory_domains = {TypeMemoryDomain::host_normal};
  specification.min_alignment_bytes = 64U;
  specification.mutability = PayloadMutability::immutable_after_publish;
  return TypeDescriptor::create(specification);
}

// ksj.coil-compression-basis: One complex basis mapping physical receive channels to virtual channels for coil compression.
// Structural payload: complex_float32 row_major_contiguous rank 2 [virtual_channel, physical_channel].
// Payload semantics: {"completion":"The matrix completely defines the immutable compression transform for its calibration key.","dimension_meanings":{"physical_channel":"physical_receive_channel","virtual_channel":"compressed_receive_channel"},"numeric_encoding":"little_endian_interleaved_ieee754_binary32_real_imaginary","payload_role":"coil_compression_basis_matrix"}
// Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; calibration keying and basis provenance remain control-plane artifacts."}
inline constexpr std::string_view kCoilCompressionBasisTypeRef = "ksj.coil-compression-basis";

[[nodiscard]] inline Result<TypeDescriptor> coil_compression_basis() {
  TypeDescriptorSpec specification;
  specification.type_ref = std::string(kCoilCompressionBasisTypeRef);
  specification.payload_kind = PayloadKind::buffer_handle;
  specification.element_type = ElementType::complex_float32;
  specification.rank = 2U;
  specification.dimensions = {"virtual_channel", "physical_channel"};
  specification.layout = LayoutKind::row_major_contiguous;
  specification.strides = StrideKind::canonical;
  specification.explicit_byte_strides = {};
  specification.allowed_memory_domains = {TypeMemoryDomain::host_normal};
  specification.min_alignment_bytes = 64U;
  specification.mutability = PayloadMutability::immutable_after_publish;
  return TypeDescriptor::create(specification);
}

// ksj.coil-image-frame: One complex reconstructed Cartesian image frame retaining one value per receive channel at every pixel.
// Structural payload: complex_float32 row_major_contiguous rank 3 [ky, kx, channel].
// Payload semantics: {"completion":"Every image pixel and receive channel for the logical frame is present before publication.","dimension_meanings":{"channel":"receive_channel_at_pixel","kx":"image_column_from_cartesian_readout_axis","ky":"image_row_from_cartesian_phase_encode_axis"},"numeric_encoding":"little_endian_interleaved_ieee754_binary32_real_imaginary","payload_role":"complex_coil_image_frame"}
// Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; scan and image-frame metadata remain control-plane artifacts."}
inline constexpr std::string_view kCoilImageFrameTypeRef = "ksj.coil-image-frame";

[[nodiscard]] inline Result<TypeDescriptor> coil_image_frame() {
  TypeDescriptorSpec specification;
  specification.type_ref = std::string(kCoilImageFrameTypeRef);
  specification.payload_kind = PayloadKind::buffer_handle;
  specification.element_type = ElementType::complex_float32;
  specification.rank = 3U;
  specification.dimensions = {"ky", "kx", "channel"};
  specification.layout = LayoutKind::row_major_contiguous;
  specification.strides = StrideKind::canonical;
  specification.explicit_byte_strides = {};
  specification.allowed_memory_domains = {TypeMemoryDomain::host_normal};
  specification.min_alignment_bytes = 64U;
  specification.mutability = PayloadMutability::immutable_after_publish;
  return TypeDescriptor::create(specification);
}

// ksj.complex-image-frame: One complex reconstructed two-dimensional image plane after channel combination or model-based reconstruction.
// Structural payload: complex_float32 row_major_contiguous rank 2 [ky, kx].
// Payload semantics: {"completion":"Every complex output pixel for the logical frame is present before publication.","dimension_meanings":{"kx":"image_column_from_cartesian_readout_axis","ky":"image_row_from_cartesian_phase_encode_axis"},"numeric_encoding":"little_endian_interleaved_ieee754_binary32_real_imaginary","payload_role":"reconstructed_complex_image_plane"}
// Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; scan and image-frame metadata remain control-plane artifacts."}
inline constexpr std::string_view kComplexImageFrameTypeRef = "ksj.complex-image-frame";

[[nodiscard]] inline Result<TypeDescriptor> complex_image_frame() {
  TypeDescriptorSpec specification;
  specification.type_ref = std::string(kComplexImageFrameTypeRef);
  specification.payload_kind = PayloadKind::buffer_handle;
  specification.element_type = ElementType::complex_float32;
  specification.rank = 2U;
  specification.dimensions = {"ky", "kx"};
  specification.layout = LayoutKind::row_major_contiguous;
  specification.strides = StrideKind::canonical;
  specification.explicit_byte_strides = {};
  specification.allowed_memory_domains = {TypeMemoryDomain::host_normal};
  specification.min_alignment_bytes = 64U;
  specification.mutability = PayloadMutability::immutable_after_publish;
  return TypeDescriptor::create(specification);
}

// ksj.sensitivity-map: One complex spatial coil sensitivity map used by sensitivity-encoded reconstruction or adaptive coil combination.
// Structural payload: complex_float32 row_major_contiguous rank 3 [ky, kx, channel].
// Payload semantics: {"completion":"Every image pixel and channel sensitivity required by the calibration key is present before publication.","dimension_meanings":{"channel":"receive_channel_at_pixel","kx":"image_column_from_cartesian_readout_axis","ky":"image_row_from_cartesian_phase_encode_axis"},"numeric_encoding":"little_endian_interleaved_ieee754_binary32_real_imaginary","payload_role":"coil_sensitivity_map"}
// Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; calibration keying and sensitivity-map provenance remain control-plane artifacts."}
inline constexpr std::string_view kSensitivityMapTypeRef = "ksj.sensitivity-map";

[[nodiscard]] inline Result<TypeDescriptor> sensitivity_map() {
  TypeDescriptorSpec specification;
  specification.type_ref = std::string(kSensitivityMapTypeRef);
  specification.payload_kind = PayloadKind::buffer_handle;
  specification.element_type = ElementType::complex_float32;
  specification.rank = 3U;
  specification.dimensions = {"ky", "kx", "channel"};
  specification.layout = LayoutKind::row_major_contiguous;
  specification.strides = StrideKind::canonical;
  specification.explicit_byte_strides = {};
  specification.allowed_memory_domains = {TypeMemoryDomain::host_normal};
  specification.min_alignment_bytes = 64U;
  specification.mutability = PayloadMutability::immutable_after_publish;
  return TypeDescriptor::create(specification);
}

// ksj.noncartesian-kspace-frame: One complete multi-channel non-Cartesian k-space sample frame with its trajectory carried on a separate typed port.
// Structural payload: complex_float32 channel_major_contiguous rank 2 [channel, sample].
// Payload semantics: {"completion":"All non-Cartesian samples for the logical frame are present before publication.","dimension_meanings":{"channel":"receive_channel","sample":"noncartesian_kspace_sample"},"numeric_encoding":"little_endian_interleaved_ieee754_binary32_real_imaginary","payload_role":"noncartesian_kspace_samples"}
// Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; trajectory association and scan metadata remain control-plane artifacts."}
inline constexpr std::string_view kNoncartesianKspaceFrameTypeRef = "ksj.noncartesian-kspace-frame";

[[nodiscard]] inline Result<TypeDescriptor> noncartesian_kspace_frame() {
  TypeDescriptorSpec specification;
  specification.type_ref = std::string(kNoncartesianKspaceFrameTypeRef);
  specification.payload_kind = PayloadKind::buffer_handle;
  specification.element_type = ElementType::complex_float32;
  specification.rank = 2U;
  specification.dimensions = {"channel", "sample"};
  specification.layout = LayoutKind::channel_major_contiguous;
  specification.strides = StrideKind::canonical;
  specification.explicit_byte_strides = {};
  specification.allowed_memory_domains = {TypeMemoryDomain::host_normal};
  specification.min_alignment_bytes = 64U;
  specification.mutability = PayloadMutability::immutable_after_publish;
  return TypeDescriptor::create(specification);
}

// ksj.trajectory-frame: One float32 non-Cartesian trajectory frame aligned sample-for-sample with a non-Cartesian k-space frame.
// Structural payload: float32 row_major_contiguous rank 2 [sample, coordinate].
// Payload semantics: {"completion":"Every trajectory coordinate for the logical frame's non-Cartesian samples is present before publication.","dimension_meanings":{"coordinate":"trajectory_coordinate","sample":"noncartesian_kspace_sample"},"numeric_encoding":"little_endian_ieee754_binary32","payload_role":"noncartesian_sampling_trajectory"}
// Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; trajectory units and scan metadata remain control-plane artifacts."}
inline constexpr std::string_view kTrajectoryFrameTypeRef = "ksj.trajectory-frame";

[[nodiscard]] inline Result<TypeDescriptor> trajectory_frame() {
  TypeDescriptorSpec specification;
  specification.type_ref = std::string(kTrajectoryFrameTypeRef);
  specification.payload_kind = PayloadKind::buffer_handle;
  specification.element_type = ElementType::float32;
  specification.rank = 2U;
  specification.dimensions = {"sample", "coordinate"};
  specification.layout = LayoutKind::row_major_contiguous;
  specification.strides = StrideKind::canonical;
  specification.explicit_byte_strides = {};
  specification.allowed_memory_domains = {TypeMemoryDomain::host_normal};
  specification.min_alignment_bytes = 64U;
  specification.mutability = PayloadMutability::immutable_after_publish;
  return TypeDescriptor::create(specification);
}

// ksj.image-frame: One reconstructed two-dimensional float32 scalar image plane used by the implemented Cartesian reconstruction and image-ops operators.
// Structural payload: float32 row_major_contiguous rank 2 [ky, kx].
// Payload semantics: {"dimension_meanings":{"kx":"image_column_from_cartesian_readout_axis","ky":"image_row_from_cartesian_phase_encode_axis"},"intensity":"One float32 scalar per output pixel. The Cartesian reconstruction emits finite non-negative magnitudes; later image Operators own any range or non-finite transformation semantics.","numeric_encoding":"little_endian_ieee754_binary32","payload_role":"reconstructed_scalar_image_plane"}
// Metadata semantics: {"kind":"none","meaning":"No per-item metadata bytes are defined; scan and plan metadata remain control-plane artifacts."}
inline constexpr std::string_view kImageFrameTypeRef = "ksj.image-frame";

[[nodiscard]] inline Result<TypeDescriptor> image_frame() {
  TypeDescriptorSpec specification;
  specification.type_ref = std::string(kImageFrameTypeRef);
  specification.payload_kind = PayloadKind::buffer_handle;
  specification.element_type = ElementType::float32;
  specification.rank = 2U;
  specification.dimensions = {"ky", "kx"};
  specification.layout = LayoutKind::row_major_contiguous;
  specification.strides = StrideKind::canonical;
  specification.explicit_byte_strides = {};
  specification.allowed_memory_domains = {TypeMemoryDomain::host_normal};
  specification.min_alignment_bytes = 64U;
  specification.mutability = PayloadMutability::immutable_after_publish;
  return TypeDescriptor::create(specification);
}

// ksj.control-message: One immutable host-resident opaque control or diagnostic message envelope for generic public-adapter and control-plane graph ports.
// Structural payload: none opaque rank 0 [].
// Payload semantics: {"dimension_meanings":{},"message_contract":"The handle denotes one complete immutable host-resident control or diagnostic envelope. Its payload representation, ownership details, and internal fields are opaque to generic graph adapters; only this TypeRef establishes compatibility.","numeric_encoding":"opaque_provider_defined_message_handle","payload_role":"opaque_control_or_diagnostic_message_envelope"}
// Metadata semantics: {"kind":"none","meaning":"No separately-addressable metadata bytes are defined. Any message details travel inside the opaque handle under its owning component's contract."}
inline constexpr std::string_view kControlMessageTypeRef = "ksj.control-message";

[[nodiscard]] inline Result<TypeDescriptor> control_message() {
  TypeDescriptorSpec specification;
  specification.type_ref = std::string(kControlMessageTypeRef);
  specification.payload_kind = PayloadKind::message_handle;
  specification.element_type = ElementType::none;
  specification.rank = 0U;
  specification.dimensions = {};
  specification.layout = LayoutKind::opaque;
  specification.strides = StrideKind::canonical;
  specification.explicit_byte_strides = {};
  specification.allowed_memory_domains = {TypeMemoryDomain::host_normal};
  specification.min_alignment_bytes = 8U;
  specification.mutability = PayloadMutability::immutable_after_publish;
  return TypeDescriptor::create(specification);
}

// ismrmrd.acquisition: One immutable host-resident opaque ISMRMRD acquisition message envelope accepted at a public PipelineDefinition ingress.
// Structural payload: none opaque rank 0 [].
// Payload semantics: {"dimension_meanings":{},"message_contract":"The handle denotes one complete ISMRMRD acquisition envelope, including its acquisition header and any sample or trajectory payload owned by the ISMRMRD binding. Generic graph code neither decodes nor retains internal fields outside the owning message-handle contract.","numeric_encoding":"opaque_ismrmrd_acquisition_message_handle","payload_role":"ismrmrd_acquisition_message_envelope"}
// Metadata semantics: {"kind":"none","meaning":"No separately-addressable metadata bytes are defined. ISMRMRD acquisition header and attribute semantics remain inside the opaque message handle."}
inline constexpr std::string_view kIsmrmrdAcquisitionTypeRef = "ismrmrd.acquisition";

[[nodiscard]] inline Result<TypeDescriptor> ismrmrd_acquisition() {
  TypeDescriptorSpec specification;
  specification.type_ref = std::string(kIsmrmrdAcquisitionTypeRef);
  specification.payload_kind = PayloadKind::message_handle;
  specification.element_type = ElementType::none;
  specification.rank = 0U;
  specification.dimensions = {};
  specification.layout = LayoutKind::opaque;
  specification.strides = StrideKind::canonical;
  specification.explicit_byte_strides = {};
  specification.allowed_memory_domains = {TypeMemoryDomain::host_normal};
  specification.min_alignment_bytes = 8U;
  specification.mutability = PayloadMutability::immutable_after_publish;
  return TypeDescriptor::create(specification);
}

// ismrmrd.waveform: One immutable host-resident opaque ISMRMRD waveform message envelope accepted at a public PipelineDefinition ingress.
// Structural payload: none opaque rank 0 [].
// Payload semantics: {"dimension_meanings":{},"message_contract":"The handle denotes one complete ISMRMRD waveform envelope, including its waveform header and waveform data owned by the ISMRMRD binding. Generic graph code neither decodes nor retains internal fields outside the owning message-handle contract.","numeric_encoding":"opaque_ismrmrd_waveform_message_handle","payload_role":"ismrmrd_waveform_message_envelope"}
// Metadata semantics: {"kind":"none","meaning":"No separately-addressable metadata bytes are defined. ISMRMRD waveform header and sample semantics remain inside the opaque message handle."}
inline constexpr std::string_view kIsmrmrdWaveformTypeRef = "ismrmrd.waveform";

[[nodiscard]] inline Result<TypeDescriptor> ismrmrd_waveform() {
  TypeDescriptorSpec specification;
  specification.type_ref = std::string(kIsmrmrdWaveformTypeRef);
  specification.payload_kind = PayloadKind::message_handle;
  specification.element_type = ElementType::none;
  specification.rank = 0U;
  specification.dimensions = {};
  specification.layout = LayoutKind::opaque;
  specification.strides = StrideKind::canonical;
  specification.explicit_byte_strides = {};
  specification.allowed_memory_domains = {TypeMemoryDomain::host_normal};
  specification.min_alignment_bytes = 8U;
  specification.mutability = PayloadMutability::immutable_after_publish;
  return TypeDescriptor::create(specification);
}

// ismrmrd.image: One immutable host-resident opaque ISMRMRD image message envelope accepted at a public PipelineDefinition egress.
// Structural payload: none opaque rank 0 [].
// Payload semantics: {"dimension_meanings":{},"message_contract":"The handle denotes one complete ISMRMRD image envelope, including its image header, pixels, and attributes owned by the ISMRMRD binding. Generic graph code neither decodes nor retains internal fields outside the owning message-handle contract.","numeric_encoding":"opaque_ismrmrd_image_message_handle","payload_role":"ismrmrd_image_message_envelope"}
// Metadata semantics: {"kind":"none","meaning":"No separately-addressable metadata bytes are defined. ISMRMRD image header, pixel, and attribute semantics remain inside the opaque message handle."}
inline constexpr std::string_view kIsmrmrdImageTypeRef = "ismrmrd.image";

[[nodiscard]] inline Result<TypeDescriptor> ismrmrd_image() {
  TypeDescriptorSpec specification;
  specification.type_ref = std::string(kIsmrmrdImageTypeRef);
  specification.payload_kind = PayloadKind::message_handle;
  specification.element_type = ElementType::none;
  specification.rank = 0U;
  specification.dimensions = {};
  specification.layout = LayoutKind::opaque;
  specification.strides = StrideKind::canonical;
  specification.explicit_byte_strides = {};
  specification.allowed_memory_domains = {TypeMemoryDomain::host_normal};
  specification.min_alignment_bytes = 8U;
  specification.mutability = PayloadMutability::immutable_after_publish;
  return TypeDescriptor::create(specification);
}

[[nodiscard]] inline Result<TypeDescriptor> resolve(const std::string_view type_ref) {
  if (type_ref == kKspaceFrameTypeRef) {
    return kspace_frame();
  }
  if (type_ref == kNoiseCalibrationFrameTypeRef) {
    return noise_calibration_frame();
  }
  if (type_ref == kNoiseModelTypeRef) {
    return noise_model();
  }
  if (type_ref == kPhaseReferenceFrameTypeRef) {
    return phase_reference_frame();
  }
  if (type_ref == kPhaseModelTypeRef) {
    return phase_model();
  }
  if (type_ref == kCoilCompressionBasisTypeRef) {
    return coil_compression_basis();
  }
  if (type_ref == kCoilImageFrameTypeRef) {
    return coil_image_frame();
  }
  if (type_ref == kComplexImageFrameTypeRef) {
    return complex_image_frame();
  }
  if (type_ref == kSensitivityMapTypeRef) {
    return sensitivity_map();
  }
  if (type_ref == kNoncartesianKspaceFrameTypeRef) {
    return noncartesian_kspace_frame();
  }
  if (type_ref == kTrajectoryFrameTypeRef) {
    return trajectory_frame();
  }
  if (type_ref == kImageFrameTypeRef) {
    return image_frame();
  }
  if (type_ref == kControlMessageTypeRef) {
    return control_message();
  }
  if (type_ref == kIsmrmrdAcquisitionTypeRef) {
    return ismrmrd_acquisition();
  }
  if (type_ref == kIsmrmrdWaveformTypeRef) {
    return ismrmrd_waveform();
  }
  if (type_ref == kIsmrmrdImageTypeRef) {
    return ismrmrd_image();
  }
  return Status::NotFound("No executable TypeDescriptor is registered for type_ref '" + std::string(type_ref) + "'.");
}

// clang-format on

} // namespace ksj::recon::types
