add_executable(ksj_optimization_backend_benchmark optimization_backend_benchmark.cpp)

ksj_target_enable_benchmark_defaults(ksj_optimization_backend_benchmark)
target_include_directories(ksj_optimization_backend_benchmark PRIVATE "${CMAKE_CURRENT_LIST_DIR}/..")
target_link_libraries(ksj_optimization_backend_benchmark PRIVATE KSpaceJet::optimization)
ksj_set_executable_runtime_path(ksj_optimization_backend_benchmark)
