#pragma once

/// Public dense-array umbrella API with KSpaceJet row-major Pooled owners and borrowed Views.

#include "kspacejet/array/dimensions.hpp"
#include "kspacejet/array/scalar_traits.hpp"
#include "kspacejet/array/slicing.hpp"
#include "kspacejet/array/views.hpp"
#include "kspacejet/array/initialization.hpp"
#include "kspacejet/array/indexing.hpp"
#include "kspacejet/array/iteration.hpp"
#include "kspacejet/array/copy.hpp"
#include "kspacejet/array/permutation.hpp"
#include "kspacejet/array/transforms.hpp"
#include "kspacejet/array/reductions.hpp"
#include "kspacejet/array/reshaping.hpp"
#include "kspacejet/array/differencing.hpp"
#include "kspacejet/array/decimation.hpp"
#include "kspacejet/array/pooled_array4d.hpp"
#include "kspacejet/array/pooled_cube.hpp"
#include "kspacejet/array/pooled_image.hpp"
#include "kspacejet/array/pooled_matrix.hpp"
#include "kspacejet/array/pooled_vector.hpp"
#include "kspacejet/array/packing.hpp"
#include "kspacejet/array/dimwise.hpp"
#include "kspacejet/array/elementwise.hpp"
#include "kspacejet/array/selection.hpp"
#include "kspacejet/array/complex.hpp"
#include "kspacejet/array/layout_conversion.hpp"
